import type { MbtiContent } from '../types'

export const mbtiEs: MbtiContent = {
  moduleLabel: 'MODULE 03 | COURT PERSONALITY',
  title: 'MBTI del bádminton',
  subtitle: '20 preguntas para conocer tu personalidad en la pista · tu pareja ideal y la que más te cuesta · espejo con jugadores profesionales',
  disclaimer: 'Es solo un test para divertirse, no una evaluación psicológica.',
  progress: '{done}/{total} preguntas',
  submit: 'Ver mi personalidad en la pista',
  incomplete: 'Todavía te quedan {n} preguntas por responder; termina el test para ver el resultado.',

  axes: {
    EI: { name: 'Dirección de la energía', first: 'E Extrovertido', second: 'I Introvertido' },
    SN: { name: 'Estilo de golpe', first: 'S Sólido · fundamentos', second: 'N Intuitivo · engaños' },
    TF: { name: 'Forma de decidir', first: 'T Racional', second: 'F Emocional' },
    JP: { name: 'Estilo de ritmo', first: 'J Planificador', second: 'P Espontáneo' },
  },

  questions: {
    m01: {
      text: 'En dobles, un drive va justo al medio entre tu compañero y tú, ¿qué haces?',
      a: 'Gritas "¡Mía!" y te lanzas directo a por ella',
      b: 'No dices nada: la coge quien la tenga más a mano, por pura complicidad',
    },
    m02: {
      text: 'Si solo pudieras dominar una habilidad, ¿cuál eliges?',
      a: 'Un clear que llega limpio a la línea de fondo, golpe tras golpe',
      b: 'Una finta en la red que deja al rival mareado y clavado en el sitio',
    },
    m03: {
      text: 'En una pachanga, el rival canta fuera una bola que ha tocado la línea, y tú lo has visto clarísimo, ¿qué haces?',
      a: 'Lo dices en el momento: "Ha tocado línea", y el punto es para quien le corresponde',
      b: 'Lo dejas pasar: es solo un punto y no merece la pena estropear el buen rollo',
    },
    m04: {
      text: 'Cuando quieres quedar para jugar el fin de semana, ¿qué sueles hacer?',
      a: 'Reservas la pista con días de antelación y ya tienes la hora y a la gente confirmadas',
      b: 'Miras en el grupo dónde hay pista libre o falta gente, y te vas sin pensarlo',
    },
    m05: {
      text: 'Alguien pregunta en el grupo "¿quién juega el sábado?", ¿tú qué haces normalmente?',
      a: 'Añades tu nombre a la lista en silencio, sin decir nada más',
      b: 'Contestas enseguida y con entusiasmo: "¡Yo! ¡Contad conmigo!", y de paso etiquetas a varios habituales para que se apunten',
    },
    m06: {
      text: 'El rival tiene una colocación perfecta y no le encuentras ningún hueco, ¿qué haces?',
      a: 'Cambias de golpe el ritmo o la dirección: una dejada cortada al cruce, un amago, y ves cómo reacciona',
      b: 'Sigues moviéndolo a las cuatro esquinas, desgastándolo poco a poco con calidad y paciencia',
    },
    m07: {
      text: 'Tu compañero de dobles encadena dos errores seguidos, ¿cuál es tu primera reacción?',
      a: 'Le das una palmadita: "Tranquilo, a por el siguiente", y calmas primero los ánimos',
      b: 'Le dices directamente: "Estás un poco retrasado, en el próximo punto cambiamos de posición"',
    },
    m08: {
      text: 'Antes de entrar a la pista, tu calentamiento suele ser...',
      a: 'Lo decides sobre la marcha según cómo te notes: si hoy te apetece empezar por la red, empiezas por la red',
      b: 'Sigues siempre la misma rutina: estiramientos, footwork, primero peloteo de clears y luego dejadas y remates',
    },
    m09: {
      text: 'Metes un remate potente y ganas el punto directo, ¿cómo reaccionas?',
      a: 'Cierras el puño, gritas "¡Vamos!" y chocas la mano con tu compañero',
      b: 'Vuelves a tu posición sin inmutarte, felicitándote solo por dentro',
    },
    m10: {
      text: 'Después de ver un partido de altísimo nivel, ¿qué es lo que más te gustaría imitar?',
      a: 'El ritmo de footwork del jugador y cómo recupera la posición después de cada golpe',
      b: 'Esa dejada cortada de revés y las fintas en la red que hace el jugador',
    },
    m11: {
      text: 'Tienes que encontrar a toda prisa una pareja de dobles mixtos en el grupo, ¿qué es lo que más valoras?',
      a: 'Que vuestra técnica y vuestro estilo se complementen, y que haya opciones de ganar',
      b: 'Que os lo paséis bien jugando y os llevéis bien; ganar o perder es lo de menos',
    },
    m12: {
      text: 'Por la tarde tienes un partido contra alguien que conoces bien, ¿qué haces?',
      a: 'Planeas la táctica de antemano: si tiene el revés débil, le cargas el fondo de pista de revés todo el partido',
      b: 'Entras a la pista, peloteas unos golpes y vas improvisando según lo que veas',
    },
    m13: {
      text: 'Es tu primera vez en un pabellón nuevo, vas a echar una pachanga y no conoces a nadie, ¿qué haces?',
      a: 'Te quedas calentando y observando a un lado, y esperas a que alguien te llame',
      b: 'Te acercas tú y preguntas: "¿Os falta gente? ¡Contad conmigo!"',
    },
    m14: {
      text: 'Haces una red con efecto perfecta y el rival apenas consigue devolver un globo corto, ¿qué haces?',
      a: 'Amagas con un remate potente y en el último momento sueltas una dejada suave para engañarlo',
      b: 'Rematas hacia abajo con firmeza: la forma más segura de ganar el punto',
    },
    m15: {
      text: 'Pierdes un partido muy reñido y de vuelta a casa, ¿en qué piensas?',
      a: 'En esos peloteos largos, qué gusto (o qué rabia) daban; la cabeza se te queda en la pista',
      b: 'En repasar qué golpes elegiste mal y cómo corregirlos la próxima vez',
    },
    m16: {
      text: 'Si abres tu bolsa de bádminton, ¿qué es más probable que te encuentres?',
      a: 'Todo metido de cualquier manera: sales ligero y, si te falta algo, ya lo pedirás prestado o lo comprarás en el pabellón',
      b: 'Cada cosa en su sitio: antes de salir repasas el cordaje, el grip, el agua y los volantes de repuesto',
    },
    m17: {
      text: 'Pierdes tres puntos seguidos y vas cuesta abajo, ¿cómo sueles recuperarte?',
      a: 'Te animas a gritos a ti mismo y a tu compañero, recuperando el empuje con la voz',
      b: 'Te colocas las cuerdas, respiras hondo y, en silencio, vuelves a poner orden en tu ritmo',
    },
    m18: {
      text: 'Cuando tus compañeros de pista comentan tu juego, ¿qué es lo más probable que te critiquen?',
      a: '"Eres demasiado predecible, se ve venir adónde vas a mandar la bola"',
      b: '"Te sobran florituras: hasta una bola sencilla la tienes que adornar con una finta"',
    },
    m19: {
      text: 'El rival es claramente más flojo que tú, pero juega con muchas ganas y muy en serio, ¿qué haces?',
      a: 'Juegas como siempre; tomárselo en serio es la forma de respetarlo',
      b: 'Bajas un poco el ritmo y alargas los puntos, para que todos disfrutéis del partido',
    },
    m20: {
      text: 'Terminas un set y ves que tu plan no ha funcionado; en el segundo set...',
      a: 'Cambias al "plan B" que ya tenías pensado antes del partido',
      b: 'Ajustas sobre la marcha, según el instinto del momento',
    },
  },

  types: {
    ISTJ: {
      nickname: 'El Muro Humano',
      emoji: '🧱',
      tagline: 'Tú remata, que yo lo devuelvo todo.',
      desc: 'Eres el rival que más quebraderos de cabeza da en el pabellón: tranquilo, sin prisas, clears que llegan a la línea de fondo, dejadas que rozan la red, defensas del remate golpe a golpe. Confías en los fundamentos, no en la suerte: si un punto se puede ganar en diez golpes, no arriesgas en tres. Al rival no lo matas de un golpe, lo desgastas hasta que falla. Tu partido es como un plan escrito de antemano: sólido y tranquilizador.',
      strengths: ['Pocos errores no forzados, y en los puntos clave no flaqueas', 'Defensa del remate muy sólida, capaz de convertir los peloteos largos en tu propio ritmo', 'Disciplina en el entrenamiento, técnica muy limpia'],
      weaknesses: ['Te falta variedad: los rivales que ya te conocen acaban encontrándote el punto débil', 'Cuando vas por detrás te cuesta arriesgar, y remontar se te hace lento'],
      partnerWhy: 'Mejor pareja: ESTP, el Artillero de los Puntos Clave. Los dos confiáis en los fundamentos y decidís según el marcador y los puntos débiles del rival: leéis el juego igual. Uno es introvertido y tranquilo, el otro extrovertido y pasional; uno planifica, el otro improvisa: juntos repartís bien la energía y el ritmo.',
      clashWhy: 'Pareja que más te cuesta: INFJ, el Lector de Mentes en la Red. Los dos sois tranquilos e introvertidos, y también planificadores; parece que encajáis, pero uno solo confía en los fundamentos y el otro vive de la intuición y el engaño, uno decide por el marcador y el otro por el instinto: al final cada uno va a lo suyo.',
      pro: 'An Se-young, jugadora activa de individual femenino, es justo este Muro Humano: su cobertura defensiva es casi perfecta y desgasta al rival a base de constancia y resistencia.',
      tips: ['En cada entrenamiento dedica 10 minutos a un golpe con más riesgo, como la dejada cortada al cruce o una finta en la red, para darle un punto de sorpresa a tu solidez', 'En los partidos de práctica ponte una regla: si vas 3 puntos por detrás, cambia el ritmo aunque sea una vez'],
    },
    ISFJ: {
      nickname: 'El Ángel Guardián',
      emoji: '😇',
      tagline: 'Tú lánzate hacia delante, que yo cubro detrás.',
      desc: 'En dobles eres quien cubre en silencio: si tu compañero pierde posición en la red, tú ya has retrocedido al fondo; si falla, lo primero que dices es "tranquilo". No buscas el golpe vistoso, solo que cada bola se devuelva bien y con seguridad, tapando poco a poco los huecos de tu pareja. En el grupo de amigos eres el compañero más solicitado, porque jugar contigo da tranquilidad.',
      strengths: ['Gran sentido de la cobertura: casi no se te escapan las bolas al medio ni por detrás', 'Estabilidad emocional: eres el calmante de tu pareja', 'Fundamentos sólidos, con mucha calidad en la defensa y en los golpes de transición'],
      weaknesses: ['Cuidas tanto a los demás que a veces cedes hasta las bolas de remate fácil', 'Te cuesta expresarte, y cuando hay que cambiar de táctica no te atreves a hablar'],
      partnerWhy: 'Mejor pareja: ESFP, la Estrella de la Pachanga. Los dos confiáis en los fundamentos y os importa cómo se siente el juego: los valores coinciden; uno cubre en silencio y el otro anima el ambiente, uno sigue la rutina y el otro va a su aire, y os complementáis genial.',
      clashWhy: 'Pareja que más te cuesta: INTJ, el Maestro del Tablero. Los dos sois tranquilos e introvertidos, y os gusta planificar con antelación; parece que encajáis, pero uno solo confía en los fundamentos y el otro vive de la variedad y la estrategia, uno cuida los sentimientos del compañero y el otro solo razona: con el tiempo cuesta entenderse.',
      pro: 'Jia Yifan, actual jugadora de dobles femeninos, es este Ángel Guardián: remate potente desde el fondo y una cobertura defensiva enorme que sostiene a su pareja.',
      tips: ['Ponte un objetivo de ataque: cierra la red o remata al menos 3 veces por set por iniciativa propia', 'En cada cambio de lado di en voz alta una idea táctica, como "vamos a su revés", para practicar decir lo que piensas'],
    },
    ESTJ: {
      nickname: 'El CEO de la Pista',
      emoji: '📋',
      tagline: 'Colocación, rotación y táctica: antes de empezar ya lo tengo todo organizado.',
      desc: 'Juegas como si dirigieras un proyecto: primero ves dónde es débil el rival, luego decides quién va delante y quién detrás, y lo ejecutas con disciplina. En dobles gritas "¡tuya!", "¡mía!" en voz alta, y si hay confusión lo corriges al instante. Confías en unos fundamentos sólidos y en un reparto de roles muy claro; lo que no soportas es jugar sin ningún plan. Jugar contigo no siempre es cómodo, pero casi siempre se gana.',
      strengths: ['Gran capacidad de ejecutar la táctica, dicho y hecho', 'Comunicación clara, roles muy definidos en dobles', 'Entrenamiento regular, técnica completa y sólida'],
      weaknesses: ['Necesidad de control algo excesiva, que puede hacer que tu pareja se sienta "mandada"', 'Cuando el plan se rompe te cuesta adaptarte y te pones nervioso'],
      partnerWhy: 'Mejor pareja: ISTP, el Cañón Silencioso. Los dos confiáis en los fundamentos y decidís por el marcador: el criterio de juego coincide; tú marcas la táctica en voz alta y lo planificas todo, tu pareja remata en silencio desde el fondo según lo que pida cada momento; uno extrovertido y otro introvertido, uno planificador y otro espontáneo: muy eficaces juntos.',
      clashWhy: 'Pareja que más te cuesta: ENFJ, el Alma del Equipo. A los dos os gusta hablar alto y marcar el ritmo con planificación: os parecéis mucho, pero uno solo confía en los fundamentos y el marcador, el otro vive de las emociones y la variedad; los dos queréis dirigir la pista, y eso acaba en roces.',
      pro: 'Viktor Axelsen, ya retirado, es este CEO de la Pista: remates muy picados desde el fondo, potencia y precisión a partes iguales, dejando el partido organizado al milímetro.',
      tips: ['En dobles dale a tu pareja un único consejo clave por set, y guarda el resto para después del partido', 'Programa un partido de práctica a la semana "sin plan", solo para entrenar la improvisación'],
    },
    ESFJ: {
      nickname: 'El Líder Pasional',
      emoji: '📣',
      tagline: 'Quien más grita en la pista, siempre, soy yo.',
      desc: 'Eres el motor del ambiente en la pista: gritas cuando ganas el punto, y también cuando lo pierdes, para animaros a ti y a tu pareja. Juegas en serio y respetas las normas, y no te saltas ni el calentamiento ni el entrenamiento; también eres quien organiza quedadas y mete gente nueva en el grupo. Tu energía enciende toda la pista, solo que cuando te acaloras, el brazo también se te tensa.',
      strengths: ['Mucha garra: eres capaz de levantar el ánimo de tu pareja', 'Disciplina: calentamiento y entrenamiento siempre muy regulares', 'Fuerte espíritu de equipo, buena comunicación en dobles'],
      weaknesses: ['Los altibajos de ánimo afectan directamente a tus golpes; con los nervios aprietas de más', 'Te importa demasiado el ambiente y te distraes fácil si el rival te provoca'],
      partnerWhy: 'Mejor pareja: ISFP, el Gato Salvavidas. Los dos confiáis en los fundamentos y os importa cómo se siente el juego: los valores coinciden; tú animas a gritos y organizas los entrenamientos con plan, tu pareja recorre la pista salvando bolas en silencio, a su aire; uno extrovertido y otro introvertido, uno planificador y otro espontáneo: encajáis muy bien.',
      clashWhy: 'Pareja que más te cuesta: ENTJ, el General de la Pista. A los dos os gusta gritar y planificar: parece que encajáis, pero uno confía en los fundamentos y se fija en el ambiente y los sentimientos, y el otro vive de la variedad y la estrategia y solo atiende a la lógica y al marcador; los dos queréis mandar en la pista, y ninguno cede.',
      pro: 'Carolina Marín, ya retirada, es esta Líder Pasional: le encantaba atacar el volante en el punto más alto, subir el ritmo y encadenar ataques, y con sus característicos gritos se venía arriba y metía presión al rival.',
      tips: ['Practica una "respiración de punto clave": dos respiraciones hondas antes de sacar en los momentos decisivos', 'Guarda los gritos para después de anotar el punto, y en el peloteo concéntrate en el footwork y la recuperación de posición'],
    },
    ISTP: {
      nickname: 'El Cañón Silencioso',
      emoji: '🧊',
      tagline: 'Hablo poco; el que habla es mi remate.',
      desc: 'Casi no dices nada en la pista, pero cada remate tuyo pesa. No te complicas con tácticas elaboradas: si hay un globo corto, saltas; si hay ocasión, rematas, limpio y directo. Confías en el instinto del cuerpo y en la mano entrenada, reaccionas rápido y, aunque te acorralen, encuentras un golpe con calma. Si te preguntan la táctica después del partido, solo dices: "lo he visto y he rematado".',
      strengths: ['Ataque decidido, remates de mucha calidad', 'Cabeza fría, no te alteras en los puntos clave', 'Reacción rápida, resuelves las bolas inesperadas con limpieza'],
      weaknesses: ['Te comunicas poco, y en dobles tu pareja no siempre sabe qué estás pensando', 'Dependes demasiado del remate, te falta variedad en los peloteos'],
      partnerWhy: 'Mejor pareja: ESTJ, el CEO de la Pista. Los dos confiáis en los fundamentos y decidís por el marcador: el criterio coincide; tu pareja marca la táctica en voz alta y lo planifica todo, tú rematas en silencio desde el fondo según lo que pida cada momento; uno extrovertido y otro introvertido, uno planificador y otro espontáneo: una combinación muy limpia.',
      clashWhy: 'Pareja que más te cuesta: INFP, el Artista Inspirado. Los dos sois tranquilos y os gusta improvisar en el momento: parece que encajáis, pero uno solo confía en los fundamentos y el marcador, el otro vive de la inspiración y las sensaciones; ninguno habla mucho, y el que es difícil de leer sigue siéndolo, así que os quedáis atascados.',
      pro: 'Fu Haifeng, ya retirado, es el representante de este Cañón Silencioso: zurdo de remate demoledor, uno de sus remates desde el fondo llegó a medirse a 332 km/h.',
      tips: ['En dobles practica avisar en voz alta: en cada bola al medio, di "mía" o "tuya"', 'En cada entrenamiento añade una serie de "remate + dejada": tras dos remates seguidos, mete obligatoriamente una dejada o una dejada cortada'],
    },
    ESTP: {
      nickname: 'El Artillero de los Puntos Clave',
      emoji: '🔥',
      tagline: 'Cuanto más importa el punto, más ganas tengo de saltar.',
      desc: 'Naciste para competir: cuanto más apretado está el marcador, más te enciendes. Te gusta atacar por iniciativa, rematar en cuanto hay ocasión, y celebrar los buenos golpes a puño cerrado. No te gusta planificar de antemano; se te da bien encontrar la sensación dentro del propio duelo, y en cuanto el rival muestra un hueco, te lanzas. Tu juego es vistoso y directo, aunque también es el que más fácil convierte el partido en un pulso de ataque puro.',
      strengths: ['Mentalidad de gran competición, te atreves con los puntos clave', 'Mucha potencia de ataque, aprovechas las ocasiones como nadie', 'Reacción rápida, te adaptas enseguida al rival'],
      weaknesses: ['Te precipitas con facilidad: tras varios ataques seguidos bajas físicamente y aumentan los errores', 'Te impacienta el peloteo largo, y en los intercambios de muchos golpes te desordenas'],
      partnerWhy: 'Mejor pareja: ISTJ, el Muro Humano. Los dos confiáis en los fundamentos y decidís por el marcador y los puntos débiles: leéis el juego igual; tú atacas e improvisas, tu pareja aguanta con calma detrás; uno extrovertido y otro introvertido, uno espontáneo y otro planificador, os complementáis a la perfección.',
      clashWhy: 'Pareja que más te cuesta: ENFP, el Rey de los Trucos. Los dos sois extrovertidos y os gusta improvisar: el carácter se parece, pero uno solo confía en el marcador y los fundamentos, y el otro vive de la inspiración, los trucos y el estado de ánimo; los dos queréis marcar el ritmo, y ninguno cede.',
      pro: 'Lin Dan, ya retirado, es este Artillero de los Puntos Clave: cuanto más importante era el punto, más subía el ritmo y más atacaba, convirtiendo la pista en su terreno.',
      tips: ['Practica los "tres golpes de paciencia": si la ocasión no es lo bastante buena, mueve al rival tres golpes antes de saltar a rematar', 'Anota tus errores por set para identificar en qué momentos te precipitas más'],
    },
    ISFP: {
      nickname: 'El Gato Salvavidas',
      emoji: '🐈',
      tagline: '¿Creías que esa bola estaba muerta? Todavía puede volver.',
      desc: 'Hablas poco, pero siempre sorprendes al rival: una bola que parecía imposible, tú la salvas con una zancada y un giro de muñeca. Juegas guiado por la sensación del cuerpo, con un footwork ligero y reflejos muy vivos, y no te gusta encorsetarte en rutinas fijas. Cuando estás en racha vuelas por toda la pista; cuando el día es normal, aguantas punto a punto a puro nervio.',
      strengths: ['Gran cobertura defensiva, se te da muy bien salvar bolas', 'Footwork ágil, sales muy rápido', 'Buena resistencia mental, no te rindes fácilmente en ninguna bola'],
      weaknesses: ['Te falta un plan de ataque propio, y a menudo te quedas atrapado defendiendo', 'Tu nivel depende mucho del estado de ánimo, con altibajos notables'],
      partnerWhy: 'Mejor pareja: ESFJ, el Líder Pasional. Los dos confiáis en los fundamentos y os importa cómo se siente el juego: los valores coinciden; tu pareja anima a gritos y lo organiza todo con plan, tú recorres la pista salvando bolas en silencio, a tu aire; uno extrovertido y otro introvertido, uno planificador y otro espontáneo: muy compenetrados.',
      clashWhy: 'Pareja que más te cuesta: INTP, el Científico del Golpe Raro. Los dos sois tranquilos y os gusta improvisar: parece que encajáis, pero uno solo confía en los fundamentos y las sensaciones, el otro vive de la lógica y los experimentos raros; cuando algo falla en la coordinación, ninguno de los dos habla, y el problema se queda ahí.',
      pro: 'Akane Yamaguchi, jugadora activa de individual femenino, es este Gato Salvavidas: mide apenas 1,56 m, pero recupera bola tras bola gracias a la velocidad y la paciencia.',
      tips: ['Después de salvar una bola, entrena el "primer golpe de contraataque": en vez de seguir levantando globos, pasa a drive o empuje al fondo', 'Antes del partido escribe 3 objetivos sencillos, para que tu nivel no dependa solo del estado de ánimo'],
    },
    ESFP: {
      nickname: 'La Estrella de la Pachanga',
      emoji: '🎉',
      tagline: '¿Para qué echo pachangas? ¡Para pasármelo en grande, y punto!',
      desc: 'Contigo en la pista, el pabellón nunca se queda apagado. Te encanta echar una pachanga con desconocidos, jugar a tope y reírte fuerte; un buen remate te alegra la noche entera. Tu juego es directo y con mucho fuego, y cuando tienes el día, no hay quien te pare. No te preocupa mucho la táctica ni el plan, lo que te importa es que el partido sea divertido, así que quien juega contigo siempre dice: "¡la próxima repetimos!".',
      strengths: ['Mucho contagio: animas a toda la pista', 'Ataque con pasión, cuando tienes el día la potencia es tremenda', 'Gran capacidad de adaptación, encajas con cualquier pareja'],
      weaknesses: ['Te distraes con facilidad, y cuando vas ganando sueles relajarte', 'Entrenas poco de forma específica, y tus carencias técnicas se quedan sin corregir'],
      partnerWhy: 'Mejor pareja: ISFJ, el Ángel Guardián. Los dos confiáis en los fundamentos y os importa cómo se siente el juego: los valores coinciden; tú animas la pista por delante, improvisando, tu pareja cubre en silencio y con orden detrás; muy buena combinación.',
      clashWhy: 'Pareja que más te cuesta: ENTP, el Ilusionista de la Red. Los dos sois extrovertidos y os gusta improvisar: el carácter se parece, pero uno confía en los fundamentos y solo le importan el ambiente y los sentimientos, y el otro vive de los trucos y solo atiende a la lógica; los dos queréis ser el centro de la pista, y os la disputáis.',
      pro: 'Huang Dongping, en activo en dobles mixtos, es esta estrella de presencia arrolladora: cerrando la red, empujando y matando en la red es un peligro constante, y en cuanto pisa la zona de red todas las miradas van hacia ella.',
      tips: ['Ponte un pequeño objetivo cada vez que juegues, como "hoy practico la bola de transición de revés", para que la diversión también traiga mejora', 'Cuando vayas ganando, recuérdate "tres golpes más de seguridad", para que no te remonten con un marcador amplio a favor'],
    },
    INTJ: {
      nickname: 'El Maestro del Tablero',
      emoji: '♟️',
      tagline: 'El destino del tercer golpe ya lo decidí en el primero.',
      desc: 'Cada punto lo juegas como una partida de ajedrez: al sacar ya tienes pensado dónde irá el tercer golpe; con clears y dejadas vas sacando al rival del centro paso a paso, y esperas a que aparezca el hueco para atacar. Eres tranquilo, paciente, casi nunca te alteras, y hasta cuando fallas analizas la causa con la cabeza fría. Tus fintas no son para lucirte, son parte del plan completo. El rival muchas veces pierde sin saber en qué golpe empezó todo.',
      strengths: ['Gran capacidad de planificación táctica, se te da muy bien mover y colocar al rival', 'Emocionalmente estable, con calma en los puntos clave', 'Buena observación y análisis, mejoras rápido'],
      weaknesses: ['Cuando el plan se rompe te cuesta reaccionar', 'Demasiado racional: a veces pareces frío, y tu pareja no sabe qué piensas'],
      partnerWhy: 'Mejor pareja: ENTP, el Ilusionista de la Red. A los dos os gusta la variedad y decidís con lógica y marcador: el criterio coincide; tú diseñas el plan desde el fondo, tu pareja improvisa fintas en la red; uno introvertido y otro extrovertido, uno planificador y otro espontáneo: os complementáis muy bien.',
      clashWhy: 'Pareja que más te cuesta: ISFJ, el Ángel Guardián. Los dos sois tranquilos e introvertidos, y os gusta planificar: parece que encajáis, pero a ti solo te importa la variedad y la estrategia, a tu pareja solo los fundamentos; uno razona y el otro cuida los sentimientos: con el tiempo cuesta entenderos.',
      pro: 'Kento Momota, ya retirado, es este Maestro del Tablero: con control y paciencia extremos, va arrastrando al rival a su propio ritmo golpe a golpe.',
      tips: ['Prepara un "plan B": lleva dos estrategias a cada partido, y cambia de inmediato si la primera no funciona', 'En dobles, di en voz alta los puntos débiles que ves en el rival, no te los guardes solo para ti'],
    },
    INTP: {
      nickname: 'El Científico del Golpe Raro',
      emoji: '🧪',
      tagline: 'Este golpe no sale en ningún manual, pero quiero probarlo.',
      desc: 'Sientes una curiosidad infinita por el "por qué se juega así". Mientras otros entrenan el clear, tú investigas el ángulo de tu dejada cortada de revés y el gesto exacto de tus fintas en la red. A menudo sacas golpes que dejan al rival descolocado, y a veces también pierdes puntos fáciles por probar algo nuevo. No te gustan las rutinas fijas: te encanta experimentar en pleno partido. Ganar está bien, pero entender un golpe nuevo te hace todavía más feliz.',
      strengths: ['Mucha creatividad, tus golpes son difíciles de anticipar', 'Buen análisis de los detalles técnicos', 'Reacción rápida, te atreves a probar cosas nuevas'],
      weaknesses: ['Fundamentos poco firmes: hasta una bola simple la complicas', 'Te obsesionas fácil, y experimentas demasiado en pleno partido'],
      partnerWhy: 'Mejor pareja: ENTJ, el General de la Pista. A los dos os gusta la variedad y decidís con lógica: el criterio coincide; tu pareja dirige en voz alta y marca el plan, tú experimentas en la pista a tu aire; uno extrovertido y otro introvertido, uno planificador y otro espontáneo: una combinación muy eficaz.',
      clashWhy: 'Pareja que más te cuesta: ISFP, el Gato Salvavidas. Los dos sois tranquilos y os gusta improvisar: parece que encajáis, pero uno solo se guía por la lógica y el experimento, el otro por los fundamentos y las sensaciones; cuando algo falla en la coordinación, ninguno de los dos habla, y el problema sigue ahí.',
      pro: 'Peter Gade, ya retirado, es el legendario Científico del Golpe Raro: su famoso "doble movimiento" desmontaba una y otra vez la anticipación del rival.',
      tips: ['Ponte una "cuota de experimentos": como máximo 3 golpes nuevos por set, el resto juégalo con el golpe de más porcentaje', 'Entrena una vez por semana multivolante básico, para reforzar la solidez del clear, la dejada y el remate'],
    },
    ENTJ: {
      nickname: 'El General de la Pista',
      emoji: '🧭',
      tagline: 'Hazme caso: todo a su revés.',
      desc: 'Eres el general nato de la pista: en los primeros golpes ya ves el punto débil del rival y organizas al momento cómo se coloca tu pareja y hacia dónde va la bola. Sabes usar la variedad, alternando empuje al fondo, red con efecto y dejada en la red en el saque y el resto, hasta meter al rival en la situación que tú has diseñado. Tienes objetivos claros, quieres ganar, y confías en que el plan lleva a la victoria. Lo único es que a veces "diriges" tanto que tu pareja acaba agobiada.',
      strengths: ['Lees el partido muy rápido y encuentras enseguida el punto débil del rival', 'Mucho liderazgo, unificas la táctica en dobles', 'Ataque con niveles y mucha variedad'],
      weaknesses: ['Exiges mucho a tu pareja, y eso puede presionarla', 'Te importa demasiado ganar, y cuando el partido no fluye te pones nervioso'],
      partnerWhy: 'Mejor pareja: INTP, el Científico del Golpe Raro. A los dos os gusta la variedad y decidís con lógica: el criterio coincide; tú diriges en voz alta y marcas el plan, tu pareja experimenta en la pista a su aire; uno extrovertido y otro introvertido, uno planificador y otro espontáneo: muy eficaces juntos.',
      clashWhy: 'Pareja que más te cuesta: ESFJ, el Líder Pasional. A los dos os gusta hablar alto y planificar: os parecéis mucho, pero tú vives de la variedad y solo te fijas en la lógica y el marcador, y tu pareja confía en los fundamentos y solo mira el ambiente y los sentimientos; los dos queréis dirigir la pista, y eso acaba en roces.',
      pro: 'Zheng Siwei, ya retirado, es este General de la Pista: velocidad y explosividad enormes desde el fondo, con ataques continuos que arrastraban el partido a su propio ritmo.',
      tips: ['En dobles, reconoce primero algo bueno de tu pareja antes de dar un consejo', 'Cuando vayas perdiendo, ajusta solo un aspecto cada vez, y evita cambiar de táctica constantemente'],
    },
    ENTP: {
      nickname: 'El Ilusionista de la Red',
      emoji: '🎭',
      tagline: 'Ese golpe en la red es mi sorpresa para ti.',
      desc: 'Eres el mago de la red: empujes, red con efecto, red cruzada, matadas en la red, todo con un toque de finta, y el rival siempre va medio golpe tarde. Te gusta retar a los mejores, y más aún ganarles de una forma que no esperaban; hasta te permites alguna sonrisa provocadora al otro lado de la red. Piensas rápido y hablas rápido, y en la pista se te ocurren ideas sin parar. Eso sí, con tanto truco, a veces hasta una bola sencilla se te complica.',
      strengths: ['Técnica de red muy fina, con muchas fintas', 'Reflejos y manos rápidas, se te da genial cerrar la red', 'Muchos recursos, capaz de romper el ritmo del rival'],
      weaknesses: ['Te arriesgas por lucirte, y eso hace que tus errores sean irregulares', 'Poca paciencia, no te gustan los peloteos largos ni defender mucho rato'],
      partnerWhy: 'Mejor pareja: INTJ, el Maestro del Tablero. A los dos os gusta la variedad y decidís con lógica y marcador: el criterio coincide; tu pareja diseña el plan desde el fondo, tú improvisas fintas en la red; uno introvertido y otro extrovertido, uno planificador y otro espontáneo, os complementáis genial.',
      clashWhy: 'Pareja que más te cuesta: ESFP, la Estrella de la Pachanga. Los dos sois extrovertidos y os gusta improvisar: el carácter se parece, pero tú vives de la lógica y la variedad, y tu pareja confía en los fundamentos y solo le importan el ambiente y los sentimientos; los dos queréis ser el centro de la pista, y os la disputáis.',
      pro: 'Kevin Sanjaya Sukamuljo, ya retirado, es este Ilusionista de la Red en persona: manos rapidísimas y muchas fintas que dejaban al rival sin entender nada.',
      tips: ['Ponle "condiciones de uso" a tus fintas: úsalas solo cuando el rival ya ha movido el peso del cuerpo', 'Entrena una vez por semana multivolante de defensa, para ganar paciencia en los momentos en los que estás a la defensiva'],
    },
    INFJ: {
      nickname: 'El Lector de Mentes en la Red',
      emoji: '🔮',
      tagline: 'Todavía no has golpeado y yo ya te estaba esperando ahí.',
      desc: 'Se te da muy bien "leer" a las personas: la colocación y la orientación de pala del rival, las costumbres y el ánimo de tu pareja, todo lo ves. Hablas poco, pero siempre apareces en el sitio justo, cerrando la red hasta hacer dudar al rival de si le lees la mente. Juegas con tu propio ritmo y tu plan, y te importa mucho la complicidad con tu pareja. Lo que más disfrutas no es rematar, sino ese momento en el que los dos jugáis con una fluidez perfecta.',
      strengths: ['Gran capacidad de anticipación y lectura del juego', 'Buen sentido para cerrar la red, con el timing muy afinado', 'Entiendes a tu pareja y se te da muy bien crear complicidad'],
      weaknesses: ['Te cuesta expresarte, y las ideas se te quedan muchas veces solo por dentro', 'Te importa demasiado lo que siente el otro, y con una pareja muy dominante tiendes a callarte'],
      partnerWhy: 'Mejor pareja: ENFP, el Rey de los Trucos. A los dos os gusta la variedad y os importa cómo se siente el juego: los valores coinciden; tú lees el juego y cierras la red en silencio, tu pareja improvisa animando la pista; uno introvertido y otro extrovertido, uno planificador y otro espontáneo, muy compenetrados.',
      clashWhy: 'Pareja que más te cuesta: ISTJ, el Muro Humano. Los dos sois tranquilos e introvertidos, y os gusta planificar: parece que encajáis, pero a ti te gusta la variedad y las sensaciones, a tu pareja solo los fundamentos y el marcador; a menudo no sabéis lo que el otro está pensando.',
      pro: 'Huang Yaqiong, ya retirada, es esta Lectora de Mentes en la Red: cerraba la red con mucha iniciativa, colocaba la bola con precisión y siempre llegaba un paso antes al sitio donde el rival quería dejarla.',
      tips: ['En cada set cuéntale a tu pareja algo que hayas visto, como "le gusta dejarla en la red en paralelo"', 'Entrena a matar en la red por iniciativa propia, para convertir tu anticipación en puntos'],
    },
    INFP: {
      nickname: 'El Artista Inspirado',
      emoji: '🎨',
      tagline: 'Ganar está bien, pero un golpe bonito es mejor todavía.',
      desc: 'Juegas como si crearas una obra: un revés ligero, una dejada cortada inesperada, son tus "obras" favoritas. No te gustan las rutinas rígidas, sueles dejarte llevar por la inspiración, y cuando estás en racha tus golpes son impredecibles, hasta el rival tiene ganas de aplaudirte. Te importa mucho cómo se siente el juego, y ese ánimo se nota en tus golpes: cuando estás feliz, todo fluye; cuando estás bajo, encadenas errores.',
      strengths: ['Toque de mano muy fino, golpes llenos de imaginación', 'Muchas fintas, difícil de anticipar', 'Disfrutas jugar de verdad, con una pasión duradera'],
      weaknesses: ['Poca regularidad, con altibajos notables', 'No te gustan los duelos de desgaste ni la preparación física, y tu físico acaba siendo un punto débil'],
      partnerWhy: 'Mejor pareja: ENFJ, el Alma del Equipo. A los dos os gusta la variedad y os importa cómo se siente el juego: los valores coinciden; tu pareja anima en voz alta y dirige el equipo con plan, tú sacas golpes inspirados en silencio, a tu aire; uno extrovertido y otro introvertido, uno planificador y otro espontáneo, encajáis muy bien.',
      clashWhy: 'Pareja que más te cuesta: ISTP, el Cañón Silencioso. Los dos sois tranquilos y os gusta improvisar: parece que encajáis, pero tú vives de la inspiración y las sensaciones, tu pareja solo de los fundamentos y el resultado; cuando algo falla, ninguno de los dos habla, y cuesta mucho generar complicidad.',
      pro: 'Tai Tzu-ying, ya retirada, es esta Artista Inspirada: golpes muy variados, muchísimas fintas y un juego en el que cada golpe parece improvisado.',
      tips: ['Fija un pequeño ritual antes del partido, como el orden del calentamiento o la respiración, para que el ánimo influya menos en tu nivel', 'Entrena físico una vez por semana, para que la inspiración vaya acompañada de piernas que aguanten'],
    },
    ENFJ: {
      nickname: 'El Alma del Equipo',
      emoji: '🦁',
      tagline: 'Doy un grito y todo el equipo despierta.',
      desc: 'En dobles eres el líder espiritual: un solo grito tuyo puede encender a tu pareja y también apagar el ánimo del rival. Se te da bien atacar y organizar desde la red, y ves el estado de ánimo de tu compañero, sabes cuándo animarlo y cuándo avisarlo. Te gusta jugar con objetivo y con plan, y sobre todo te gusta mejorar acompañado. Con alguien así en el equipo, nadie tira la toalla fácilmente.',
      strengths: ['Mucho contagio, capaz de arrastrar a tu pareja y al equipo', 'Buen sentido de organización en la red', 'Buena comunicación, cuidas el ánimo de tu pareja'],
      weaknesses: ['Te implicas emocionalmente en exceso, y cuando pierdes te culpas fácilmente', 'Te preocupa tanto el estado de tu pareja que a veces descuidas tu propia técnica'],
      partnerWhy: 'Mejor pareja: INFP, el Artista Inspirado. A los dos os gusta la variedad y os importa cómo se siente el juego: los valores coinciden; tú animas en voz alta y organizas con plan, tu pareja saca golpes inspirados en silencio, a su aire; uno extrovertido y otro introvertido, uno planificador y otro espontáneo: mucha chispa juntos.',
      clashWhy: 'Pareja que más te cuesta: ESTJ, el CEO de la Pista. A los dos os gusta hablar alto y planificar: os parecéis mucho, pero a ti te importan los sentimientos y la variedad, a tu pareja solo los fundamentos y el marcador; los dos queréis dirigir la pista, y eso genera roces.',
      pro: 'Chen Qingchen, ya retirada, es esta Alma del Equipo en persona: rápida en la red y con muchas intercepciones, capaz de encender a toda la pareja con un solo grito.',
      tips: ['Guarda la energía emocional para después de anotar el punto y en los cambios de lado; en el peloteo concéntrate en la técnica', 'Resérvate un entrenamiento individual a la semana para reforzar tus propios puntos débiles'],
    },
    ENFP: {
      nickname: 'El Rey de los Trucos',
      emoji: '🌈',
      tagline: '¡Hoy también voy a sacar un golpe que arranque un "¡wow!" a toda la pista!',
      desc: 'Eres la fuente de diversión del pabellón: remate de revés, devoluciones por la espalda, fintas en la red, quieres probarlo todo. Juegas guiado por el ánimo y la inspiración: cuando estás bien, ni los mejores pueden contigo; cuando estás mal, puedes perder varios puntos seguidos. Te encanta conocer gente nueva y vas allá donde haya partido. Para ti, lo importante del bádminton no es ganar o perder, sino ese "¡wow!" que arranca a toda la pista.',
      strengths: ['Mucha creatividad y espectáculo, sacas golpes sorprendentes', 'Mucho entusiasmo, te integras rápido en cualquier partido', 'Buen toque de mano, te atreves con técnicas difíciles'],
      weaknesses: ['Poca regularidad, fallas fácil en bolas sencillas', 'No te gusta el entrenamiento repetitivo, y los fundamentos se quedan con huecos'],
      partnerWhy: 'Mejor pareja: INFJ, el Lector de Mentes en la Red. A los dos os gusta la variedad y os importa cómo se siente el juego: los valores coinciden; tú animas la pista por delante, improvisando, tu pareja lee el juego y cierra la red en silencio, con su plan; uno extrovertido y otro introvertido, uno espontáneo y otro planificador: muy compenetrados.',
      clashWhy: 'Pareja que más te cuesta: ESTP, el Artillero de los Puntos Clave. Los dos sois extrovertidos y os gusta improvisar: el carácter se parece, pero tú vives de los trucos y las sensaciones, y tu pareja solo confía en los fundamentos, el marcador y el resultado; los dos queréis marcar el ritmo, y ninguno cede.',
      pro: 'Taufik Hidayat, ya retirado, es el pionero de este Rey de los Trucos: su remate de revés era descomunal y sus fintas en la red dejaban al rival totalmente descolocado.',
      tips: ['Cada vez que aprendas un truco nuevo, entrena también el fundamento que lo sostiene, como el clear de revés junto al remate de revés', 'En el partido asegura primero los puntos de inicio, y deja el "espectáculo" para después'],
    },
  },

  result: {
    title: 'Tu personalidad en la pista',
    strengthsTitle: 'Puntos fuertes',
    weaknessesTitle: 'Puntos débiles',
    bestPartnerTitle: 'Mejor pareja',
    worstPartnerTitle: 'Pareja que más te cuesta',
    proTitle: 'Espejo profesional',
    tipsTitle: 'Consejos para mejorar',
    retake: 'Repetir el test',
    missing: 'No se ha encontrado este resultado, vuelve a hacer el test.',
  },
}
