import type { TalentContent } from '../types'

export const talentEs: TalentContent = {
  list: { sep: ', ', colon: ': ', open: ' (', close: ')' },

  form: {
    moduleLabel: 'MODULE 01 | TALENT & BODY TYPE',
    title: 'Evaluación de talento y estilo de bádminton',
    subtitle: 'Encaje profundo entre cuerpo y capacidades · Recomendación de individuales y dobles · Referencia de jugadores espejo',
    fields: {
      sex: 'Sexo · GENDER',
      age: 'Edad · AGE',
      heightCm: 'Altura · HEIGHT (CM)',
      weightKg: 'Peso · WEIGHT (KG)',
      wingspanCm: 'Envergadura · WINGSPAN (CM)',
      yearsPlaying: 'Años jugando · EXP',
      hand: 'Mano · HAND',
      freq: 'Frecuencia · FREQ',
      preference: 'Preferencia · PREFER',
    },
    wingspanHint: 'Brazos en cruz, distancia entre la punta de un dedo y la del otro; si no lo indicas, se estima igual a tu altura y el resultado es solo orientativo.',
    abilitiesTitle: 'Autoevaluación de las ocho capacidades',
    abilitiesHint: 'Compara cada nivel con su descripción concreta y elige el que más se ajuste a tu nivel actual; cuanto más específico seas, más preciso será el resultado.',
    testsTitle: 'Pruebas de campo (opcional)',
    testsHint: 'Si tienes datos de alguna prueba, se promediarán con tu autoevaluación para afinar el resultado; también puedes enviar el formulario sin haberlas hecho.',
    prefsTitle: 'Tus gustos de juego',
    prefsHint: 'No hay respuestas buenas ni malas: elige lo que más se parece a cómo te gusta jugar. Influye en el estilo recomendado.',
    choose: 'Selecciona',
    submit: 'Generar mi informe de talento',
    confirmWarnings: 'Hay algunos avisos sobre tus datos. ¿Confirmas que son correctos y quieres continuar?',
    missingReport: 'Todavía no hay un informe generado. Completa primero el formulario de arriba y envíalo.',
    errors: {
      required: 'Rellena este campo',
      number: 'Introduce un número',
      range: 'Introduce un valor entre {min} y {max}',
    },
    warnings: {
      wingspanDiff: 'La envergadura que has indicado difiere bastante de tu altura; comprueba que la medida esté bien tomada (brazos en cruz, de punta a punta de los dedos).',
      bmiExtreme: 'El IMC calculado está fuera del rango habitual; comprueba que la altura y el peso estén bien introducidos.',
      minor: 'Tienes menos de 16 años: consulta este informe acompañado/a de un adulto responsable y, para planificar entrenamientos, prioriza siempre a un entrenador o entrenadora cualificado/a.',
    },
  },

  options: {
    sex: { M: 'Hombre', F: 'Mujer' },
    hand: { R: 'Diestro/a', L: 'Zurdo/a' },
    freq: {
      lt1: 'Menos de 1 vez por semana',
      '1': '1 vez por semana',
      '2-3': '2–3 veces por semana',
      '4+': 'Más de 4 veces por semana',
    },
    preference: {
      singles: 'Individuales',
      doubles: 'Dobles',
      mixed: 'Dobles mixtos',
      all: 'Todas',
    },
  },

  prefs: {
    scoring: { question: '¿Cómo disfrutas más ganando el punto?', options: { smash: 'Rematando desde el fondo', net: 'Con dejadas y engaños en la red', rally: 'Con peloteos largos hasta que falle el rival', counter: 'Defendiendo primero y contraatacando' } },
    midcourt: { question: 'Te devuelven una bola alta a media pista. Normalmente…', options: { smash: 'Remato', drop: 'Hago una dejada o una dejada cortada', push: 'Empujo al fondo para mover al rival' } },
    tempo: { question: '¿Qué ritmo de partido te gusta?', options: { fast: 'Cuanto más rápido mejor, tomar la iniciativa', grind: 'Tranquilo, desgastando poco a poco', adapt: 'Me adapto al rival' } },
    underAttack: { question: 'Cuando el rival ataca sin parar, prefieres…', options: { drive: 'Devolver con drive y plantar cara', block: 'Bloquear a la red con calma', lift: 'Levantar al fondo y reorganizarme' } },
    rally: { question: '¿Qué tipo de peloteo prefieres?', options: { short: 'Cortos: resolver en 3–5 golpes', long: 'Largos: paciencia y físico', either: 'Me da igual, depende' } },
    doublesSpot: { question: 'En dobles prefieres jugar…', options: { front: 'En la red, cerrando', back: 'En el fondo, atacando', rotate: 'Donde toque, rotando', none: 'Casi no juego dobles / no lo sé' } },
  },
  abilities: {
    power: {
      name: 'Potencia',
      hint: 'remate, salto',
      levels: [
        'El remate casi no baja, parece un simple empuje',
        'Consigues bajar el remate, pero va lento y el rival lo recibe sin problema',
        'El remate desde el suelo ya amenaza, pero el remate en salto es irregular',
        'Encadenas remates fuertes y en salto, y a menudo obligas al rival a bloquear en la red',
        'El remate te da puntos directos; el remate en salto es un arma fija',
      ],
      diag: {
        weak: 'Tu potencia está en {score}/10: al remate y al salto les falta esa fuerza de "un golpe seco"; la amenaza en el fondo de pista es limitada y el rival se atreve a darte un clear.',
        medium: 'Tu potencia está en {score}/10: consigues remates de calidad, pero tras varios seguidos la velocidad y el ángulo bajan; en los puntos clave todavía te falta ese golpe definitivo.',
        strong: 'Tu potencia ya está en {score}/10: la fuerza del remate y el salto son tu arma, el rival no se atreve a darte clears fáciles. El siguiente paso es dirigir esa fuerza al punto exacto: la dirección y el momento importan más que cada remate a máxima potencia.',
      },
      tips: {
        weak: 'Remate con multiplumas desde el sitio, centrado en el giro de tronco y el latigazo del brazo, sin buscar el salto todavía: 3 series × 15 volantes. Sentadilla con salto 3 series × 8, y zancada alterna con salto 3 series × 6 por lado, 2 veces por semana.',
        medium: 'Multiplumas combinando remate y dejada, 4 series × 12 volantes. Lanzamiento de balón medicinal con giro de tronco, 3 series × 10 por lado, y salto vertical 4 series × 6.',
        strong: 'Trabajo de precisión en remate corto y remate cortado (marca una zona objetivo), 4 series × 10 volantes. Enlace remate-subida a la red, 4 series × 6 ciclos.',
      },
    },
    endurance: {
      name: 'Resistencia',
      hint: 'peloteos largos, set decisivo',
      levels: [
        'Con 1 set ya te notas muy cansado/a',
        'Aguantas 1 partido (2 sets), pero llegas muy fatigado/a al final',
        'Aguantas 2–3 partidos seguidos, pero bajas el ritmo en el set decisivo',
        'Puedes jugar toda una noche (unas 3 horas) y seguir corriendo',
        'Ni los peloteos largos ni los partidos seguidos te hacen bajar el ritmo',
      ],
      diag: {
        weak: 'Tu resistencia está en {score}/10: en los peloteos largos el gesto se deforma y la vuelta al centro se hace lenta; los errores aumentan claramente desde la segunda mitad del segundo set.',
        medium: 'Tu resistencia está en {score}/10: aguantas un partido completo, pero bajas de ritmo con claridad en el set decisivo o en partidos seguidos.',
        strong: 'Tu resistencia ya está en {score}/10: tienes buena reserva física, así que alargar el peloteo juega a tu favor — puedes buscar activamente los intercambios largos y desgastar antes al rival.',
      },
      tips: {
        weak: 'Footwork en 6 direcciones por intervalos, 20 s de trabajo / 40 s de descanso × 8 series. Dos sesiones semanales de 20–30 minutos de aeróbico suave (carrera suave, bicicleta).',
        medium: 'Multiplumas de pista completa por intervalos, 30 s de trabajo / 30 s de descanso × 10 series. Juega 3 sets de partido de entrenamiento y anota los errores del tercer set.',
        strong: 'Mantén 1 sesión semanal de intervalos de alta intensidad. Convierte la resistencia en táctica: entrena el patrón de "estirar primero, rematar después".',
      },
    },
    reaction: {
      name: 'Reacción',
      hint: 'defensa del remate, drive',
      levels: [
        'En el drive y la defensa del remate, a menudo no llegas a levantar la raqueta a tiempo',
        'Reaccionas a los volantes lentos, pero fallas mucho con los rápidos',
        'La defensa del remate y el drive habituales los sacas, pero los golpes al cuerpo te cuestan',
        'También sacas los golpes al cuerpo y los cambios de dirección repentinos, y encima con calidad',
        'Puedes contraatacar de forma activa y anticiparte, colocándote antes que el volante',
      ],
      diag: {
        weak: 'Tu reacción está en {score}/10: cuando el rival ataca, hace drive o mata en la red, a menudo no te da tiempo a levantar la raqueta; en defensa pierdes el punto con facilidad.',
        medium: 'Tu reacción está en {score}/10: a los volantes habituales reaccionas bien, pero ante golpes al cuerpo y cambios bruscos de dirección todavía vas medio tiempo por detrás.',
        strong: 'Tu reacción ya está en {score}/10: sales rápido, la defensa del remate y el drive son tu terreno cómodo; puedes convertir esa reacción en anticipación y colocarte un paso antes.',
      },
      tips: {
        weak: 'Paso de separación más arranque en las 4 direcciones según una señal, 5 series × 10. Drive de cerca con tu pareja de entrenamiento, 6 series × 1 minuto, empezando despacio y acelerando.',
        medium: 'Multiplumas de defensa del remate (al cuerpo y a ambos lados, al azar), 4 series × 20 volantes. Ejercicio de "leer el golpe": di hacia dónde va a golpear tu compañero/a justo antes de que golpee, 3 series × 20, y anota el porcentaje de aciertos.',
        strong: 'Defensa de dos contra uno, 4 series × 2 minutos. Ejercicio de anticipación leyendo el gesto previo del rival, anotando el porcentaje de aciertos.',
      },
    },
    netTouch: {
      name: 'Toque de red',
      hint: 'red con efecto, dejada en la red',
      levels: [
        'La bola de red suele irse a la red o pasarse demasiado alta',
        'Consigues dejadas en la red, pero de calidad irregular y solo sabes hacer un tipo',
        'Dominas más o menos la red con efecto, la dejada en la red y el empuje, y de vez en cuando sale un golpe bueno',
        'Consigues efecto con giro y red cruzada, obligando a menudo al rival a dar un globo',
        'Tu juego de red es fino, con amagos, y a veces gana el punto directamente',
      ],
      diag: {
        weak: 'Tu toque de red está en {score}/10: te falta control en la red con efecto, la dejada y el empuje — la bola se va a la red o se pasa de alta, y en cuanto el rival sube a la red te mata el punto.',
        medium: 'Tu toque de red está en {score}/10: consigues dejadas aceptables, pero con poca variedad; en cuanto el rival te lee, pierdes la amenaza.',
        strong: 'Tu toque de red ya está en {score}/10: tienes finura de manos, consigues efecto con giro y red cruzada, y a menudo obligas al rival a dar un globo. El siguiente paso es enlazar esa ventaja de red con tu juego de fondo de pista.',
      },
      tips: {
        weak: 'Multiplumas de dejada en la red y red con efecto, 5 series × 20 volantes, exigiendo que pasen la red a una altura menor que una pala. Minijuego de red contra red (solo dentro de la línea de saque corto), 2 sets a 11 puntos.',
        medium: 'Con la misma preparación, elige entre red con efecto en línea, red cruzada o empuje al fondo, 3 series × 20 volantes. Ejercicio de anticipación en la red: en cuanto el volante del rival suba por encima de la cinta, mátalo o empújalo, 3 series × 15.',
        strong: 'Después de una dejada, si el rival da un globo al fondo, retrocede y remata; 4 series × 8 ciclos. Entrenamiento específico de amagos con golpe retardado, 3 series × 15 volantes.',
      },
    },
    speed: {
      name: 'Velocidad',
      hint: 'footwork en 6 direcciones, arranque',
      levels: [
        'No dominas el footwork en 6 direcciones; a menudo no llegas al volante',
        'Conoces el footwork básico, pero el arranque y la vuelta al centro son lentos',
        'Llegas bien a los desplazamientos habituales, pero los cambios de diagonal seguidos te cuestan',
        'Eres rápido/a en las cuatro direcciones y raras veces te dejan descolocado/a',
        'Cubres toda la pista y a menudo llegas pronto para golpear en un punto alto',
      ],
      diag: {
        weak: 'Tu velocidad está en {score}/10: el arranque y la vuelta al centro son lentos, los cambios de diagonal te dejan fuera de sitio, y cuando llegas la calidad del golpe también baja.',
        medium: 'Tu velocidad está en {score}/10: llegas bien a los desplazamientos habituales, pero no vuelves a tiempo ante diagonales seguidas o cambios bruscos de dirección.',
        strong: 'Tu velocidad ya está en {score}/10: tus pies son rápidos y cubres mucha pista, es la base de toda tu táctica; puedes imponer un ritmo más alto y obligar al rival a golpear en desventaja.',
      },
      tips: {
        weak: 'Footwork en 6 direcciones por partes: primero adelante-atrás, luego a los lados, y por último la pista completa, 10 repeticiones × 3 series por dirección, priorizando el gesto correcto. Comba a un tiempo, 1 minuto × 5 series, con 30 s de descanso.',
        medium: 'Footwork con órdenes al azar hacia los 6 puntos, 20 s × 8 series. Sprints de ida y vuelta a 5 metros × 10.',
        strong: 'Mantén 1–2 sesiones semanales de sprints de footwork. Convierte la velocidad en ritmo: entrena "volver rápido al centro y llegar pronto al punto alto".',
      },
    },
    rearCourt: {
      name: 'Fondo de pista',
      hint: 'clear, línea de fondo',
      levels: [
        'El clear no pasa del medio campo',
        'Llega a media pista de fondo, pero no a la línea de fondo',
        'Llega a la línea de fondo, pero muy alto y lento',
        'De derecha llega de forma estable a la línea de fondo, y por encima de la cabeza también más o menos',
        'Desde cualquier rincón consigues un clear de ataque que llega a la línea de fondo',
      ],
      diag: {
        weak: 'Tu fondo de pista está en {score}/10: el clear no llega a la línea de fondo y suele caer a media pista, así que el rival puede rematar o atacar directamente.',
        medium: 'Tu fondo de pista está en {score}/10: llegas a la línea de fondo, pero con una trayectoria demasiado alta y lenta; por encima de la cabeza y de revés todavía no llegas bien, y el rival tiene tiempo de sobra para prepararse.',
        strong: 'Tu fondo de pista ya está en {score}/10: presionas la línea de fondo de forma estable y además consigues un clear de ataque; es la base con la que controlas el partido y organizas tu ataque.',
      },
      tips: {
        weak: 'Multiplumas de clear de derecha, 4 series × 15 volantes, con el objetivo a menos de 1 metro de la línea de fondo. Gesto descompuesto en vacío (giro de hombros, preparación, giro de tronco, latigazo), frente al espejo, 3 series × 10.',
        medium: 'Clear de ataque y golpe por encima de la cabeza, 4 series × 12 volantes. Clear de revés o transición de revés, 3 series × 10 volantes.',
        strong: 'Un mismo gesto con varias opciones en el fondo (clear, dejada cortada o remate), 3 series × 20 volantes. Partido de precisión presionando la línea de fondo de forma continua.',
      },
    },
    tactics: {
      name: 'Lectura táctica',
      hint: 'colocación, mover al rival',
      levels: [
        'Con que pase la red ya te vale, no piensas en la colocación',
        'Sabes que hay que buscar el hueco, pero sueles devolver la bola cerca del rival',
        'Mueves al rival a las cuatro esquinas de forma consciente, con uno o dos patrones fijos',
        'Ajustas la dirección y el ritmo según el punto débil del rival',
        'Lees la intención del rival y le preparas la jugada con antelación',
      ],
      diag: {
        weak: 'Tu lectura táctica está en {score}/10: golpeas casi por instinto y sueles devolver la bola a donde le resulta cómoda al rival; cuando pierdes el punto tampoco tienes claro por qué.',
        medium: 'Tu lectura táctica está en {score}/10: sabes que hay que mover al rival, pero tu repertorio es limitado y no cambias cuando el rival se adapta.',
        strong: 'Tu lectura táctica ya está en {score}/10: lees al rival, cambias de dirección y ajustas la estrategia durante el partido; puedes ganar más con diseño que a base de puro esfuerzo físico.',
      },
      tips: {
        weak: 'Ponte un único objetivo por partido (por ejemplo, "atacar más el revés del rival") y revisa al terminar si lo cumpliste. "Plan de tres golpes": antes de cada punto, decide dónde colocarás el saque y el tercer golpe.',
        medium: 'Cambia de patrón principal cada set (mover al rival a las cuatro esquinas, presionar el fondo, atacar la red) en 3 sets de entrenamiento. Graba en vídeo un set y anota tus dos causas más frecuentes de pérdida de punto.',
        strong: 'Ponte restricciones (por ejemplo, prohibido rematar) e intenta ganar el set de todos modos. Prepara planes A/B según el estilo de cada rival.',
      },
    },
    mental: {
      name: 'Mentalidad',
      hint: 'puntos clave, presión',
      levels: [
        'Si encadenas puntos en contra te desmontas y a menudo te rindes',
        'En los puntos clave sueles ablandarte o precipitarte',
        'La mayoría de las veces estás estable, aunque a veces te arrastra la emoción',
        'Cuando vas por detrás en el marcador, sabes mantener la calma y remontar',
        'Cuanto más importante es el punto, más firme estás, y llegas a influir en el rival',
      ],
      diag: {
        weak: 'Tu mentalidad está en {score}/10: se te agarrotan las manos cuando vas ganando y te precipitas cuando vas perdiendo; tras varios puntos seguidos en contra, es fácil que "regales" el punto.',
        medium: 'Tu mentalidad está en {score}/10: la mayor parte del tiempo te mantienes firme, pero dudas en los puntos clave o ante rivales conocidos o fuertes.',
        strong: 'Tu mentalidad ya está en {score}/10: aguantas bien la presión, te atreves con los puntos clave y los ejecutas con firmeza; la mentalidad es tu arma oculta.',
      },
      tips: {
        weak: 'Fija una pequeña rutina antes de sacar o de restar: una respiración profunda y una palabra clave en silencio (por ejemplo, "alto, largo, firme"), en cada punto. Juega partidos de entrenamiento empezando 15:18 en contra, centrado en los puntos clave.',
        medium: 'Plan para puntos clave: a partir del 20 iguales, usa solo tus 2 patrones con mayor porcentaje de éxito. Anota en cada partido de entrenamiento los puntos clave ganados y perdidos.',
        strong: 'Usa tu ventaja mental en la táctica: cuando vayas ganando, sigue con el plan original sin volverte conservador/a. En dobles, encárgate de dar instrucciones y marcar el ritmo.',
      },
    },
  },

  tests: {
    verticalJumpCm: {
      label: 'Salto vertical',
      unit: 'cm',
      hint: 'Media sentadilla, brazos hacia atrás y luego un braceo rápido hacia arriba y adelante, salto vertical desde el sitio con los dos pies; mide dos veces y quédate con el mejor resultado.',
    },
    ropeSkip1Min: {
      label: 'Comba en 1 minuto',
      unit: 'saltos',
      hint: 'Salto a la comba a un tiempo; cuenta el número máximo de saltos en 1 minuto, siguiendo contando aunque te enredes con la cuerda.',
    },
    cooper12MinM: {
      label: 'Carrera de 12 minutos',
      unit: 'm',
      hint: 'Corre a ritmo constante durante 12 minutos completos y anota la distancia total; hazlo preferiblemente en una pista estándar y sin forzar.',
    },
    rulerDropCm: {
      label: 'Reacción con regla',
      unit: 'cm',
      hint: 'Tu compañero/a sostiene una regla vertical con el 0 a la altura entre tu pulgar y tu índice; al soltarla, ciérralos lo antes posible y anota la marca donde la has sujetado, repitiendo varias veces para promediar.',
    },
  },

  bodyTypes: {
    compactQuick: {
      name: 'Compacto y rápido (centro de gravedad bajo)',
      summary: 'Tu cuerpo es, dentro de tu sexo, de estatura baja y peso no elevado. El centro de gravedad bajo y la distancia corta de arranque son una condición favorable para arrancar y cambiar de dirección con rapidez; la dificultad natural es un punto de golpeo bajo, por lo que cubrir el fondo de pista exige más pasos para compensarlo.',
    },
    lightAgile: {
      name: 'Ligero y ágil',
      summary: 'Tu cuerpo es, dentro de tu sexo, de estatura media y peso ligero. La carga corporal baja es una condición favorable para moverte rápido y aguantar peloteos largos; tu reserva de fuerza es relativamente limitada, así que el remate y la presión continua en el fondo necesitan apoyarse en la técnica y en un trabajo de fuerza específico.',
    },
    balanced: {
      name: 'Equilibrado',
      summary: 'La proporción entre tu altura y tu peso es equilibrada: tu cuerpo no te limita a la hora de elegir ningún estilo de juego — tu estilo lo deciden sobre todo la técnica y las capacidades.',
    },
    sturdyPower: {
      name: 'Robusto y potente',
      summary: 'Tu proporción peso/altura es elevada y tienes una complexión fuerte. Si esa masa es sobre todo muscular, es una condición favorable para rematar y hacer drive con más contundencia; hay que vigilar la carga en los desplazamientos y proteger rodillas y tobillos.',
    },
    tallLean: {
      name: 'Alto y delgado',
      nameLongArms: 'Alto y de brazos largos',
      summary: 'Tu cuerpo es, dentro de tu sexo, de estatura alta y peso ligero. Un punto de golpeo alto y buen alcance son una condición favorable para presionar el fondo de pista y controlar la colocación; la dificultad natural es un centro de gravedad alto, así que la defensa en posición baja y los cambios bruscos de dirección necesitan apoyarse en el footwork y en la fuerza de piernas.',
    },
    tallPower: {
      name: 'Alto y potente',
      summary: 'Tu cuerpo es, dentro de tu sexo, de estatura alta y con buena reserva de fuerza, lo que es una condición favorable para rematar desde un punto alto; la dificultad está en el arranque y los cambios de dirección — el alcance que da tu altura necesita apoyarse en un footwork eficiente para hacerse realidad.',
    },
  },

  singles: {
    attack: {
      name: 'Atacante dominante',
      emoji: '💥',
      tagline: 'Rematar desde un punto alto y encadenar ataques para mantener al rival a la defensiva.',
      fitIntro: 'Tu encaje con el atacante dominante es del {fit}%: este estilo se apoya en la potencia y el fondo de pista para mantener al rival a la defensiva.',
      coreTactic: 'Con la misma preparación, elige entre remate fuerte, remate corto o dejada cortada para que el rival no pueda leerte; ataca sobre todo el revés del rival y los golpes al cuerpo, y remata en línea buscando el hueco. Después de rematar, sube de inmediato a la red para cerrar la bola que el rival intente devolver. Usa el clear de ataque y el empuje al fondo para obligar al rival a dar una bola a media pista y preparar así el siguiente remate.',
      opening: 'Saca sobre todo bolas cortas de red para no regalar la iniciativa; al restar, empuja al fondo o busca la red de forma activa, buscando rematar ya en el tercer golpe. En los primeros 5 puntos, tantea el lado débil del rival en la defensa del remate: ¿derecha o revés?, ¿al cuerpo o a los lados?',
      midgame: 'Alterna remate y dejada: si llevas más de 3 remates fuertes seguidos sin puntuar, cambia a dejada cortada o remate corto. Si el rival defiende bien el remate, usa la dejada cortada para llevarlo a la red y luego vuelve a presionar el fondo. Cuando estés en desventaja, no fuerces el remate: usa clear de ataque o clear para ganar tiempo y volver al centro.',
      keyPoints: 'Usa solo el recurso de puntuación con más éxito ese día, normalmente el remate al cuerpo o al revés del rival; a partir de 18 puntos no arriesgues rematando a la línea; si vas ganando, sigue presionando sin pasar de repente a un clear conservador.',
      stamina: 'En el primer set, usa más el remate corto y la dejada cortada, y menos el remate en salto; a partir de la mitad del segundo set, reserva el remate en salto solo para las bolas fáciles. En cada set, busca conscientemente 2–3 "puntos de respiro" con clears para regular la respiración; tras el cambio de lado en el set decisivo, guarda tu mejor remate para los puntos clave.',
      pitfalls: 'Confundir "rematar fuerte" con "rematar bien": la dirección y el momento importan más que la potencia. No subir a la red tras rematar, dejando que el rival tenga tiempo de defenderse. Rematar en salto sin criterio, agotando la reserva física en el segundo set. Rematar siempre al centro, dejando que el rival lo reciba parado. Girar poco el tronco y forzar solo con el brazo, lo que lesiona hombro y codo con facilidad.',
      matchups: 'Dominas al artista de la red: lo mantienes en el fondo de pista, donde su juego de manos no sirve de nada. El defensor contraatacante te domina a ti: un rival que defiende bien el remate te devuelve la fuerza en forma de contraataque; la solución es usar más dejada cortada y remate corto en vez de remate fuerte, y subir a cerrar la red sin dudarlo tras rematar. Frente al controlador de las cuatro esquinas depende de las condiciones: si mantienes la presión continua tienes ventaja, pero en cuanto te abren la pista y baja la calidad de tu remate, la ventaja pasa al controlador.',
    },
    control: {
      name: 'Controlador de las cuatro esquinas',
      emoji: '🎯',
      tagline: 'Clear a la línea de fondo, dejada cortada a la red: desgastar al rival a base de colocación y paciencia.',
      fitIntro: 'Tu encaje con el controlador de las cuatro esquinas es del {fit}%: este estilo se apoya en la resistencia y la lectura táctica para desgastar al rival con colocación y paciencia.',
      coreTactic: 'Usa el clear y la dejada cortada para llevar la bola a los dos fondos y a las dos esquinas de red, con el objetivo de que el rival corra en diagonal; golpea dos veces seguidas al mismo punto para romper su ritmo de recuperación. En cuanto la devolución del rival pierda calidad y aparezca una bola a media pista, remata sin dudarlo. Pasa la dejada pegada a la cinta para obligar al rival a dar un globo.',
      opening: 'Empieza con saques cortos de red; al restar, prioriza la dejada en la red o el empuje al fondo. En los primeros 5 puntos, observa qué esquina le cuesta más cubrir al rival.',
      midgame: 'Fija un "ángulo principal de ataque", normalmente el revés en el fondo o la red en su derecha, y golpea ahí cada 3–5 golpes; en los peloteos largos, insiste en volver siempre al centro.',
      keyPoints: 'No busques el punto con prisa: alarga el peloteo y deja que el rival falle primero; pero en cuanto aparezca una bola a media pista, tienes que rematar — no vuelvas al clear por costumbre.',
      stamina: 'Tu resistencia es tu arma: desde el primer set ya busca peloteos largos para desgastar al rival, y sube el ritmo en la segunda mitad del segundo set.',
      pitfalls: 'Solo estirar y no rematar nunca, dando clear incluso con bolas a media pista fáciles. Dejadas demasiado altas y lentas, que el rival te mata en la red. Colocación limitada a la diagonal larga, previsible para el rival. Descuidar la vuelta al centro, dejando que el rival te rompa con un solo golpe.',
      matchups: 'Dominas al defensor contraatacante, porque no le das remates de los que pueda sacar partido y lo desgastas moviéndolo; también dominas al artista de la red, porque lo llevas al fondo de pista. Frente al atacante dominante depende de las condiciones: si mantiene la presión pierdes tú, pero en cuanto baja su nivel físico ganas tú. Frente al atacante veloz también depende: en peloteos cortos gana él o ella, en peloteos largos ganas tú.',
    },
    counter: {
      name: 'Defensor contraatacante',
      emoji: '🛡️',
      tagline: 'Solo si defiendes bien puedes devolver el golpe: defensa del remate, drive y contraataque para convertir el ataque del rival en tus puntos.',
      fitIntro: 'Tu encaje con el defensor contraatacante es del {fit}%: este estilo se apoya en la reacción y la velocidad para convertir el ataque del rival en tus puntos.',
      coreTactic: 'Tres recursos en la defensa del remate: bloqueo en línea a la red, red cruzada, o drive/empuje al fondo como contraataque. Sitúate ligeramente por detrás del centro, con la pala por delante del cuerpo, y haz el paso de separación antes de cada golpe. Cuando el rival tarde en subir tras rematar, bloquea en la red para obligarlo a dar otro globo; cuando no llegue a tiempo a su posición, contraataca al hueco en línea.',
      opening: 'Pelotea con clears para tantear la calidad del remate del rival y su dirección de remate más habitual.',
      midgame: 'No temas que te rematen, pero cuídate de las combinaciones de dejada y remate seguidas; en desventaja, da un clear alto y profundo para ganar tiempo de recuperación. La señal para pasar de defender a atacar es que el remate del rival pierda calidad o que tarde en subir a la red tras rematar.',
      keyPoints: 'No regales bolas a media pista; en la defensa del remate, prioriza el bloqueo (el de menor riesgo) y deja que el error sea del rival.',
      stamina: 'El estilo defensivo es el que más desgasta las piernas; usa el clear como transición para ganar tiempo de recuperación. El set decisivo suele ser tu terreno, porque el remate del rival empieza a perder fuerza antes que tu defensa.',
      pitfalls: 'Defender sin atacar nunca, esperando siempre el error del rival. Colocarse demasiado atrás en defensa, quedando expuesto a la dejada en la red. Devolver siempre al mismo sitio en la defensa del remate, algo que el rival acaba anticipando. No llegar el clear a la línea de fondo, regalando al rival un punto de remate cómodo.',
      matchups: 'Dominas al atacante dominante, porque le devuelves su propia fuerza en forma de contraataque; también dominas al atacante veloz, porque al defenderle el ataque no le da tiempo a recolocarse. El controlador de las cuatro esquinas te domina a ti, porque no te da remates de los que sacar partido y te hace correr; la solución es cambiar de dirección de forma activa en vez de seguirle el peloteo. El artista de la red también te domina, porque te engaña el arranque con su juego de manos; la solución es adelantar medio paso tu posición de defensa.',
    },
    speed: {
      name: 'Atacante veloz',
      emoji: '⚡',
      tagline: 'Arranque rápido, remate rápido, subida a la red rápida: siempre medio tiempo por delante del rival.',
      fitIntro: 'Tu encaje con el atacante veloz es del {fit}%: este estilo se apoya en la velocidad y la reacción para reducir el tiempo de preparación del rival.',
      coreTactic: 'Adelántate a la posición para golpear en un punto más alto y más adelantado; remate corto o de ataque rápido, seguido de inmediato de una subida a la red para matar. Usa el empuje y el clear de ataque para presionar las dos esquinas de fondo del rival y acortar su tiempo de preparación; en cuanto su bola de red suba un poco, mátala o empújala.',
      opening: 'Sube el ritmo desde los tres primeros golpes: tras el saque corto de red, busca la red o ataca ya en el tercer golpe, aprovechando que el rival aún no ha entrado en ritmo.',
      midgame: 'Combina rápido y lento: tras 3–4 golpes seguidos a ritmo alto, coloca una bola de red o un clear para regular; no mantengas la máxima velocidad todo el rato porque acabas fallando tú primero.',
      keyPoints: 'Usa tu combinación de ataque más entrenada, por ejemplo restar buscando la red y encadenar con un ataque rápido; no sacrifiques la colocación solo por ir rápido.',
      stamina: 'El mayor riesgo es bajar el ritmo al final del partido; recupera la velocidad tras cada descanso de los 11 puntos. Necesitas tener siempre una buena base de resistencia por intervalos.',
      pitfalls: 'Llegar a tiempo pero golpear mal, con el punto de golpeo descolocado. Tener un único ritmo, al que el rival acaba adaptándose. Ir tan rápido que aumentan los errores. Descuidar la resistencia y bajar en el segundo set.',
      matchups: 'Dominas al artista de la red, porque al buscar la red le reduces el tiempo para hacer su juego de manos. El defensor contraatacante te domina a ti, porque tu ataque rápido, una vez defendido, no te da tiempo a recolocarte; la solución es mover al rival antes de atacar, en vez de lanzarte cuando ya está preparado. Frente al controlador de las cuatro esquinas depende de las condiciones: en peloteos cortos ganas tú, en peloteos largos gana el rival.',
    },
    allround: {
      name: 'Jugador completo',
      emoji: '🌟',
      tagline: 'Sin puntos débiles claros, capaz de atacar y defender, cambiando de plan según el rival.',
      fitIntro: 'Tu encaje con el jugador completo es del {fit}%: el valor de este estilo está en "saber cambiar", siempre que sepas cuándo hacerlo.',
      coreTactic: 'Explora antes de decidir: usa los primeros 5–8 puntos para tantear con recursos distintos y luego elige el plan que más incomode al rival. Ten un plan A y un plan B: si el ataque no funciona, cambia a mover al rival por las esquinas; si eso tampoco funciona, cambia a presionar la red. Cambia rápido entre atacar y defender: no fuerces el ataque en desventaja ni te ablandes cuando llevas la iniciativa.',
      opening: 'Varía tanto el saque como el resto para no revelar tus preferencias.',
      midgame: 'Decide tu patrón principal según el punto débil del rival; cambia el ritmo de forma activa al menos una vez por set.',
      keyPoints: 'Usa el patrón con mayor porcentaje de éxito ese día, sin lucirte innecesariamente.',
      stamina: 'El reparto de energía depende del estilo que elijas en cada momento, sin una forma fija de desgaste.',
      pitfalls: 'Saber un poco de todo pero no tener un golpe definitivo. Cambiar de plan con demasiada frecuencia, lo que te descoloca a ti mismo/a. No saber qué recurso usar en los puntos clave.',
      matchups: 'No tienes una relación de dominio fija con nadie; lo que más temes es que el rival lleve al extremo una sola cualidad y arrastre el partido a su terreno más fuerte. La respuesta es identificar pronto el punto fuerte del rival y evitarlo.',
    },
    net: {
      name: 'Artista de la red',
      emoji: '🪄',
      tagline: 'Red con efecto y red cruzada en la red: engañar con las manos para abrir huecos.',
      fitIntro: 'Tu encaje con el artista de la red es del {fit}%: este estilo se apoya en el toque de red y la lectura táctica para abrir huecos junto a la red.',
      coreTactic: 'Pasa la dejada pegada a la cinta, con efecto, para obligar al rival a dar un globo; con la misma preparación, alterna red con efecto, red cruzada y empuje, retrasando el golpe para crear el amago. En cuanto ganes el punto alto en la red, empuja a las dos esquinas de fondo del rival; en el fondo, usa la dejada cortada para atraerlo de nuevo a la red.',
      opening: 'Saca bolas cortas de red y busca tomar la iniciativa en la red ya en el tercer golpe; al restar, prioriza la dejada en la red.',
      midgame: 'Gira todo tu juego en torno a la red; en el fondo de pista no busques ganar el punto, solo llegar bien colocado/a. Ataca sobre todo el lado en el que el rival reacciona más lento en la red.',
      keyPoints: 'Usa la bola de red con la que más seguridad tengas (normalmente la dejada en la red) y evita la red cruzada de alta dificultad.',
      stamina: 'Este estilo ahorra energía en general, pero cuando te presionan el fondo necesitas capacidad de transición, así que reserva algo de energía para defender ahí.',
      pitfalls: 'Lucirte demasiado en la red y acumular errores. Transición pobre hacia el fondo de pista, quedando expuesto/a a presión constante ahí. Si el rival juega todo el rato al fondo y no te da bolas de red, te quedas sin recursos.',
      matchups: 'Dominas al defensor contraatacante, porque su posición defensiva más retrasada hace que tu juego de manos le engañe el arranque con facilidad. El atacante dominante, el atacante veloz y el controlador de las cuatro esquinas te dominan a ti: el primero te encierra en el fondo, el segundo te quita tiempo para hacer tu juego de manos buscando la red, y el tercero te lleva al fondo; en los tres casos, la solución es reforzar tu clear de fondo y tu capacidad de transición.',
    },
  },

  doubles: {
    front: {
      name: 'Especialista de red',
      emoji: '🗡️',
      tagline: 'El muro de la zona de red: cerrar la red, buscarla de forma activa y organizar los tres primeros golpes para crear ocasiones de remate a tu pareja.',
      fitIntro: 'Tu encaje con el especialista de red es del {fit}%: la reacción y el toque de red son justo las dos cualidades que más se necesitan en la red en dobles.',
      coreTactic: 'Tras el saque, levanta la pala de inmediato para cerrar la red e interceptar el bloqueo o el drive del rival, obligándolo a seguir dando globos. Tu posición se desplaza según la dirección del remate de tu pareja: si remata en línea, tú te inclinas hacia ese lado para cerrar esa línea; si remata cruzado, tú te acercas al centro. En los tres primeros golpes, busca la red con el saque y el resto, empujando o matando, para crear ocasiones de remate a tu pareja de fondo; acordad que la bola de red por el centro es siempre para la zona de red.',
      rotation: 'Si te ves obligado/a a dar un globo en la red, pasa de inmediato a la posición defensiva de lado a lado; si tu pareja pasa del fondo a la red, retrocede tú a cubrir el fondo e intercambiad los roles; si el rival manda la bola por encima de ti y tu pareja no llega, retrocede tú a atacar y que tu pareja suba; si ganas una ocasión en la red (matar, empujar), quédate en la zona de red.',
      positioning: 'En ataque, colócate cerca de la línea de saque corto, un poco por detrás del punto central; mantén la pala por encima de la cinta y el peso en la parte delantera del pie; guarda con tu pareja la formación uno delante y uno detrás, desplazándoos hacia el mismo lado.',
      positioningDont: 'No te pegues demasiado a la red, o el rival te pasará por encima con un empuje o un globo. No bajes la pala, porque entonces no podrás levantar la bola de red y solo te quedará el globo. No retrocedáis los dos a la vez al fondo, dejando la red completamente vacía. No mates bolas de medio campo al azar, quitándole a tu pareja de fondo una bola que le correspondía a ella.',
      signals: '"Mía" / "tuya" para confirmar de quién es la bola del centro; "sube" / "atrás" para indicarle a tu pareja que suba a la red o retroceda; al sacar, indica con un gesto a espaldas tuyas si el siguiente saque será corto o al fondo.',
      signalsDont: 'No esperes a que la bola esté a punto de caer para gritar "mía" o "tuya" de repente — acordadlo antes con un gesto. No sustituyas la señal clara por un sonido ambiguo. No os culpéis tras perder un punto; basta con confirmar con calma: "esa era mía".',
    },
    back: {
      name: 'Atacante de fondo',
      emoji: '💣',
      tagline: 'La artillería de los dobles: presión continua de remate desde el fondo, cubriendo las dos esquinas de fondo y dejando las ocasiones a tu pareja de red.',
      fitIntro: 'Tu encaje con el atacante de fondo es del {fit}%: este rol vive de la potencia y del fondo de pista para encadenar remates — es la "artillería" de los dobles; de los dos repartos, red o fondo, tu perfil y tu cuerpo se acercan más a este.',
      coreTactic: 'Combina remate fuerte, remate corto y dejada cortada, atacando el centro entre los dos rivales o al cuerpo; tras rematar, da medio paso adelante para seguir presionando y obligar al rival a bloquear hacia tu pareja de red. En el medio fondo, usa el drive para presionar y atacar; en desventaja, da un clear a la línea de fondo y pasad a la formación de lado a lado.',
      rotation: 'Si el rival bloquea hacia la zona de red y tu pareja no llega a tiempo, sube tú a la red y que tu pareja retroceda; si el rival da un globo cruzado, desplázate tú en horizontal para cubrir el fondo y que tu pareja de red no retroceda; si te ves obligado/a a dar un globo, pasad los dos a la formación de lado a lado.',
      positioning: 'En ataque, colócate en el medio campo hacia atrás, desplazándote hacia el mismo lado detrás de tu pareja; tras rematar en línea, mantén la posición hacia ese lado.',
      positioningDont: 'No te quedes mirando la bola en el sitio después de rematar. No ataques siempre por la misma línea. No le quites a tu pareja de red las bolas de medio campo que le tocan a ella. No fuerces el remate cuando el fondo ya está en desventaja.',
      signals: '"Yo remato, tú cierras" para repartir claramente los papeles; "el centro es mío" para confirmar de quién es esa bola; tras un fallo de tu pareja, dale un gesto de confirmación sin reprocharle nada.',
      signalsDont: 'No cambies de dirección de repente antes de rematar sin avisar, dejando a tu pareja descolocada/o. No le quites a tu pareja una bola de cierre en la red sin explicar por qué. No sustituyas el gesto de confirmación por una queja.',
    },
    rotation: {
      name: 'Rotador todoterreno',
      emoji: '🔄',
      tagline: 'Capaz de jugar tanto delante como detrás: el eslabón más rápido en el cambio entre ataque y defensa.',
      fitIntro: 'Tu encaje con el rotador todoterreno es del {fit}%: tu adaptación a la red y al fondo es parecida, y tu nivel general está por encima de la media, lo que encaja con la rotación de "quien esté más cerca, que juegue la bola".',
      coreTactic: 'Cambiad de posición según la bola: quien esté más cerca y de cara al volante, que lo juegue, y el otro/la otra que cubra. Ciclo de remate y subida a la red: uno remata y sube, el otro cubre el fondo. Paso de defensa a ataque: tras un contraataque en la defensa del remate, quien haya sacado la bola, que presione hacia delante.',
      rotation: 'El primer golpe tras el saque o el resto decide la formación inicial; después seguid la regla de "atacando uno delante y otro detrás, defendiendo lado a lado". En cada cambio, los dos os movéis en direcciones opuestas: uno sube, el otro baja.',
      positioning: 'En ataque, cambiad de posición de forma dinámica según la cercanía de la bola, sin una formación fija; en defensa, repartíos por lados, cada uno con su mitad.',
      positioningDont: 'No queráis los dos jugar la red o el fondo al mismo tiempo. No os mováis los dos hacia el mismo lado durante la rotación, dejando un hueco libre.',
      signals: '"Cambio" para indicar la rotación; "subo yo" y "atrás tú" para confirmar quién avanza y quién retrocede.',
      signalsDont: 'No os quedéis los dos en silencio esperando a que el otro se mueva primero. No sustituyáis la voz por la mirada — con el ritmo alto es fácil que se os escape.',
    },
  },

  report: {
    title: 'Tu informe de talento en bádminton',
    back: 'Volver',
    retest: 'Repetir la evaluación',
    share: 'Compartir informe',
    radarCurrent: 'Capacidad real (autoevaluación/pruebas)',
    radarTendency: 'Tendencia corporal (estimada)',
    radarNote: 'La línea discontinua es una estimación de la tendencia corporal y no representa tu nivel real; la línea continua es tu capacidad actual.',
    physicalTitle: 'Forma física',
    bodyLine: 'Forma física: {sex} | {height}cm / {weight}kg | IMC {bmi} ({band})',
    bmiBands: {
      under: 'bajo',
      lean: 'ligero',
      normal: 'moderado',
      solid: 'robusto',
      heavy: 'elevado',
    },
    wingspanLine: 'La envergadura difiere {diff} cm de tu altura, con una proporción de {ratio}.',
    wingspanAssumed: 'No indicaste tu envergadura: se ha estimado igual a tu altura, así que el resultado es solo orientativo.',
    yearsLine: 'Llevas jugando {years} años.',
    bodyTypeLabel: 'Tipo corporal',
    claimAdvantage: {
      weak: 'Tu cuerpo te da una ventaja natural para {ability}, pero tu {ability} actual es solo de {score}/10: ese potencial todavía no se ha hecho realidad.',
      medium: 'Tu cuerpo te da cierta ventaja para {ability}; tu {ability} actual es de {score}/10 — la ventaja se está haciendo realidad poco a poco, y seguirá mejorando si sigues entrenando.',
      strong: 'La ventaja corporal ya se ha hecho realidad: {ability} {score}/10.',
    },
    claimDisadvantage: {
      weak: '{ability} ({score}/10) es la dificultad natural de tu cuerpo; necesita un trabajo específico y sostenido para mejorarla.',
      medium: 'Tu cuerpo no te da ventaja natural para {ability}; estás en {score}/10, más o menos al nivel de tu tendencia corporal, con margen para mejorar.',
      strong: 'Tu cuerpo no te daba ventaja para {ability}, pero ya has llegado a {score}/10: has compensado ese punto débil con trabajo.',
    },
    ageBands: {
      youth: {
        name: 'Etapa de desarrollo juvenil (≤17 años)',
        advice: 'Tu cuerpo todavía se está desarrollando, así que la recomendación de estilo es solo orientativa: es la etapa dorada para la técnica general, la coordinación y el footwork. Entrena sobre todo técnica general, footwork, coordinación y flexibilidad; el trabajo de fuerza debe basarse en el propio peso corporal y en gestos técnicos, y las cargas altas necesitan supervisión de un entrenador o entrenadora cualificado/a; evita especializarte en un solo estilo demasiado pronto.',
      },
      prime: {
        name: 'Etapa dorada física (18–30 años)',
        advice: 'Es tu ventana física óptima: puedes probar cualquier estilo, y el atacante veloz y el atacante dominante son los que más rinden puliéndose en esta etapa. Entrena la condición física de forma sistemática (intervalos + fuerza) para tener reserva de cara al resto de tu recorrido deportivo.',
      },
      thirties: {
        name: 'Etapa de transición técnica (31–40 años)',
        advice: 'La recuperación se vuelve más lenta y la velocidad y la resistencia empiezan a bajar poco a poco; el estilo puede ir inclinándose hacia el control y los dobles. Calienta al menos 10–15 minutos; añade cada semana trabajo de fuerza para gemelo y tendón de Aquiles (elevaciones de talón, 3 series × 15); reduce en torno a un tercio las series de ejercicios de salto; al caer tras un salto en el fondo de pista, gira hacia fuera la pierna de apoyo, lo que reduce claramente el impacto sobre el tendón de Aquiles.',
      },
      forties: {
        name: 'Etapa de prioridad al control (41–50 años)',
        advice: 'La bajada de velocidad y potencia es más marcada; el controlador de las cuatro esquinas, el artista de la red y los dobles dan más rendimiento por esfuerzo. Haz 2 sesiones semanales de fuerza de piernas y core; aumenta la carga poco a poco, sin subidas bruscas; presta especial atención al tendón de Aquiles, la rodilla y el hombro; reduce los remates en salto seguidos.',
      },
      fiftyPlus: {
        name: 'Etapa de la experiencia (51 años o más)',
        advice: 'Prioriza los dobles y el control, ganando con colocación y experiencia. Añade ejercicios de equilibrio y fuerza de piernas, con 2 sesiones semanales de trabajo de fuerza; si tienes alguna enfermedad crónica o llevas mucho tiempo sin hacer ejercicio, consulta a un médico antes de empezar un entrenamiento sistemático.',
      },
    },
    strongWeak: 'Tu punto relativamente fuerte es {strong} ({strongScore}/10) y tu punto relativamente débil es {weak} ({weakScore}/10).',
    flatProfile: 'Diagnóstico del radar: tus seis capacidades están ahora al mismo nivel, sin un punto fuerte ni débil claro; ve mejorándolas una a una según las prioridades de tu estilo.',
    tacticsTitle: '🧠 Diagnóstico de lectura táctica ({score}/10)',
    mentalTitle: '💪 Diagnóstico de mentalidad ({score}/10)',
    singlesMono: 'SINGLE STRATEGY',
    singlesBand: 'Recomendación de estilo en individuales',
    singlesIntro: 'A partir de tus ocho capacidades y de tu tendencia corporal, hemos calculado tu encaje con los seis estilos de individuales, ordenados de mayor a menor puntuación.',
    doublesMono: 'DOUBLE TACTICS',
    doublesBand: 'Recomendación de rol en dobles',
    doublesIntro: 'En dobles, el reparto se divide entre "zona de red" y "fondo de pista"; cuando tu encaje con ambos es parecido y tu nivel general no es bajo, se recomienda la "rotación todoterreno".',
    fitBands: {
      high: 'Encaje alto',
      good: 'Buen encaje',
      lean: 'Tendencia inicial',
    },
    fitLine: 'Encaje {fit}% ({band})',
    fitAnalysis: 'Análisis del encaje',
    driversLine: 'Principales impulsores: {list}',
    gapsLine: 'A reforzar: {list}',
    noDrivers: 'Por ahora no hay ninguna capacidad especialmente destacada como impulsora.',
    noGaps: 'No hay ninguna capacidad que te esté frenando de forma clara.',
    runnerUp: 'Segundo estilo: {emoji} {name} · Encaje {fit}%',
    prefLabel: 'Tus gustos',
    prefAligned: 'Tus gustos de juego también apuntan a «{style}»: lo que te gusta y tus capacidades van en la misma dirección.',
    prefConflict: 'El estilo que más te gusta es «{pref}», pero hoy tus capacidades y tu cuerpo encajan mejor con «{rec}». Toma «{pref}» como objetivo a largo plazo: gana partidos con «{rec}» mientras entrenas lo que pide «{pref}».',
    prefLed: 'La recomendación «{pref}» sale sobre todo de tus gustos; mirando solo tus capacidades y tu cuerpo actuales, encajas más con «{ability}». «{pref}» es un buen objetivo, pero primero tendrás que reforzar las carencias de abajo para poder jugar así en partido.',
    prefNone: 'Este informe no tiene gustos de juego: la recomendación se basa solo en capacidades y cuerpo. Repite el test para añadirlos.',
    doublesPrefConflict: 'Prefieres jugar en «{pref}», pero tu perfil se acerca más a «{rec}»; con pareja fija puedes empezar en tu sitio favorito y volver al que mejor dominas en los puntos clave.',
    singlesLabels: {
      coreTactic: 'Táctica principal',
      opening: 'Estrategia de apertura',
      midgame: 'Control del punto medio',
      keyPoints: 'Gestión de los puntos clave',
      stamina: 'Reparto de energía',
      pitfalls: 'Errores frecuentes',
      matchups: 'Relación con otros estilos',
    },
    doublesLabels: {
      coreTactic: 'Táctica principal',
      rotation: 'Momentos de rotación',
      positioning: 'Principios de colocación',
      positioningDont: 'Errores de colocación',
      signals: 'Señales de comunicación',
      signalsDont: 'Errores en las señales',
      partner: 'Consejo de pareja',
      mixed: 'Aviso para dobles mixtos',
    },
    partner: {
      front: 'Eres «especialista de red» → busca una pareja {role} ({strength} ≥ 7): con potencia y fondo de pista destacados y buena resistencia, capaz de encadenar remates y cubrir las dos esquinas de fondo, formando contigo un equipo que se complementa en ataque y defensa.',
      back: 'Eres «atacante de fondo» → busca una pareja {role} ({strength} ≥ 7): con reacción y toque de red destacados, capaz de cerrar la red y organizar los tres primeros golpes, convirtiendo en puntos las ocasiones que creas con tus remates.',
      rotation: 'Eres «rotador todoterreno» → busca una pareja {role} que también sepa rotar y tenga más {strength} que tú: así los dos podréis cubrir la red y el fondo, y no dudaréis a la vez al rotar.',
    },
    mixedNotes: {
      conventional: 'Tu rol encaja totalmente con el reparto habitual en dobles mixtos ("mujer delante, hombre detrás"): la zona de red se encarga del saque, cerrar la red y los tres primeros golpes, y el fondo de pista cubre toda la pista y el remate continuo; basta con que cada uno cumpla su papel con normalidad.',
      femaleBack: 'El reparto habitual en dobles mixtos es "mujer delante, hombre detrás", pero tu perfil en dobles tiende al fondo de pista — en dobles femeninos puedes jugar directamente ese rol. En mixtos seguirás teniendo que asumir tareas de red: te conviene reforzar primero la reacción y el cierre de red, o bien jugar con una pareja masculina con buen nivel de red que esté dispuesto a ocupar más la zona delantera (una formación poco habitual que hay que acordar de antemano).',
      maleFront: 'En dobles mixtos, el fondo de pista suele ser tarea del hombre, pero tu perfil tiende a la zona de red. Tu ventaja en la red puede notarse en el saque, el resto buscando la red y los tres primeros golpes, aunque en los peloteos largos seguirás teniendo que retroceder al fondo; en dobles masculinos encajas mejor jugando la red.',
      rotation: 'En dobles mixtos, la zona de red se centra en interceptar en la red y el fondo de pista en cubrir toda la pista; como rotador o rotadora, puedes cubrir ambos lados, y si te mandan la bola por detrás también tienes capacidad para defender el fondo de forma puntual — eso juega a tu favor.',
    },
    mirrorTitle: 'Jugador espejo',
    singlesMirror: 'Espejo de estilo (individuales)',
    bodyMirror: 'Espejo de cuerpo (individuales)',
    doublesMirror: 'Espejo en dobles',
    alternates: 'Otras opciones',
    you: 'Tú',
    mirror: 'Espejo',
    height: 'Altura',
    weight: 'Peso',
    bmi: 'IMC',
    bmiDiffLine: 'Diferencia de IMC: {diff}',
    styleMatch: {
      primary: 'Coincide con tu estilo principal',
      secondary: 'Coincide con tu segundo estilo',
      none: 'Estilo distinto, cuerpo parecido',
    },
    status: {
      active: 'En activo',
      retired: 'Retirado/a ({year})', retiredNoYear: 'Retirado/a',
      split: 'Pareja separada',
    },
    events: {
      MD: 'Dobles masculinos',
      WD: 'Dobles femeninos',
      XD: 'Dobles mixtos',
    },
    positions: {
      front: 'Zona de red',
      back: 'Fondo de pista',
      both: 'Juega en ambas zonas',
    },
    matchedPlayer: '{name} ({position})',
    trainingTitle: 'Plan de entrenamiento',
    drills: {
      shadowFootwork: {
        name: 'Footwork en 6 direcciones por partes',
        how: 'Sin volante: primero trabaja el desplazamiento adelante-atrás, luego a los lados, y por último combínalo en el footwork completo de 6 direcciones; prioriza el gesto correcto antes que la velocidad.',
        dose: '10 repeticiones × 3 series por dirección, 2–3 veces por semana.',
      },
      fourCornerMulti: {
        name: 'Multiplumas de desplazamiento a las 4 esquinas',
        how: 'Tu compañero/a te manda volantes a las cuatro esquinas (red derecha, red revés, fondo derecha, fondo revés); vuelve al centro antes de arrancar hacia la siguiente esquina.',
        dose: '20 s de trabajo / 40 s de descanso × 8 series, 2 veces por semana.',
      },
      plyoJump: {
        name: 'Salto pliométrico de piernas',
        how: 'Sentadilla con salto y zancada alterna con salto, cuidando la amortiguación al caer; para en cuanto el gesto se deforme. Si tienes molestias en la rodilla, sustitúyelo por subidas a un escalón.',
        dose: 'Sentadilla con salto 3 series × 8, zancada alterna con salto 3 series × 6 por lado, 2 veces por semana con al menos 48 horas entre sesiones.',
      },
      smashMulti: {
        name: 'Multiplumas de remate continuo',
        how: 'Tu compañero/a te manda clears seguidos al fondo y tú rematas alternando línea, diagonal y al cuerpo; para y corrige en cuanto el gesto se deforme.',
        dose: '1 serie × 15 volantes por dirección, 3–4 series en total, con 60–90 s de descanso entre series, 2 veces por semana.',
      },
      clearToBaseline: {
        name: 'Clear a la línea de fondo',
        how: 'Multiplumas de clear de derecha, con el objetivo a menos de 1 metro de la línea de fondo; combínalo con el gesto descompuesto en vacío (giro de hombros, preparación, giro de tronco, latigazo) frente al espejo.',
        dose: 'Multiplumas 4 series × 15 volantes, gesto en vacío 3 series × 10, 2–3 veces por semana.',
      },
      netSpinning: {
        name: 'Red con efecto y dejada en la red',
        how: 'Multiplumas de dejada y red con efecto, exigiendo que el volante pase la red a una altura menor que una pala; cuando lo domines, añade la variante de elegir entre red cruzada y empuje al fondo.',
        dose: '5 series × 20 volantes, 2–3 veces por semana.',
      },
      netKillRush: {
        name: 'Entrenamiento de matar en la red',
        how: 'Tu compañero/a sube la bola de red por encima de la cinta y tú la matas o la empujas de inmediato, entrenando la primera reacción para juzgar si la bola está alta o baja.',
        dose: '3 series × 15 repeticiones, 2 veces por semana.',
      },
      defenseBlock: {
        name: 'Multiplumas de defensa del remate',
        how: 'Tu compañero/a remata desde un punto alto enfrente y tú defiendes al azar a ambos lados y al cuerpo, devolviendo con bloqueo, red cruzada o contraataque.',
        dose: '20 volantes por serie × 4 series, 2 veces por semana.',
      },
      driveExchange: {
        name: 'Duelo de drive y bloqueo',
        how: 'Dos jugadores intercambian drives en el medio campo, empezando despacio para coger el ritmo y acelerando después; el objetivo es el control de la pala, no la fuerza.',
        dose: '1 minuto × 6 series, 2 veces por semana.',
      },
      intervalCourtSprints: {
        name: 'Sprints e idas y vueltas en intervalos',
        how: 'Sprints de ida y vuelta a 5 metros, o multiplumas de pista completa en intervalos, manteniendo alta intensidad con descansos completos.',
        dose: '10 repeticiones de ida y vuelta a 5 m, o 30 s de trabajo / 30 s de descanso × 10 series, 2 veces por semana.',
      },
      rallyControl: {
        name: 'Partido con restricciones',
        how: 'Solo se permite clear, dejada y red; prohibido rematar, obligándote a ganar a base de colocación y paciencia.',
        dose: 'Sets a 11 puntos, 3 sets, 1 vez por semana.',
      },
      threeShotPatterns: {
        name: 'Patrones de los tres primeros golpes',
        how: 'Antes de cada punto, di en voz alta dónde piensas colocar el saque y el tercer golpe; tras 20 puntos, calcula el porcentaje de aciertos respecto al plan.',
        dose: '20 puntos por serie, 2 veces por semana.',
      },
      matchReview: {
        name: 'Revisión en vídeo del partido',
        how: 'Graba un set de un partido de entrenamiento y, al terminar, anota tus dos causas más frecuentes de pérdida de punto para preparar el siguiente ajuste.',
        dose: '1 partido por semana, con 15–20 minutos de revisión después.',
      },
      pressurePoints: {
        name: 'Entrenamiento de puntos clave en desventaja',
        how: 'Juega partidos de entrenamiento empezando el marcador en 15:18 en contra, usando solo tus 1–2 patrones con mayor porcentaje de éxito, centrado en gestionar los puntos clave.',
        dose: '3 sets por sesión, 1 vez por semana.',
      },
      serveRoutine: {
        name: 'Rutina fija antes de sacar o restar',
        how: 'Antes de cada saque o resto, haz una respiración profunda y repite en silencio una palabra clave (por ejemplo, "alto, largo, firme"), fijando así el gesto y el estado mental.',
        dose: 'En cada punto, mantenla durante un partido de entrenamiento completo, al menos 1 vez por semana.',
      },
    },
    flagsTitle: 'Avisos',
    flags: {
      beginner: 'Llevas menos de 1 año jugando, así que este informe te da una "dirección de desarrollo" y no un estilo ya definido; prioriza la base: agarre correcto, saque y resto de bolas de red y de fondo, clear a la línea de fondo, footwork en 6 direcciones con vuelta al centro, y dejada en la red. Te conviene al menos 1 clase semanal con un entrenador o entrenadora y no tener prisa por el remate en salto.',
      youth: 'Tu cuerpo todavía se está desarrollando, así que la recomendación de estilo es solo orientativa. Es la etapa dorada para la técnica general, la coordinación y el footwork; evita especializarte en un solo estilo demasiado pronto, y el trabajo de fuerza con cargas altas necesita supervisión de un entrenador o entrenadora cualificado/a.',
      injury30: 'A partir de los 31 años: calienta al menos 10–15 minutos; añade cada semana trabajo de fuerza para gemelo y tendón de Aquiles (elevaciones de talón, 3 series × 15); reduce en torno a un tercio las series de ejercicios de salto; al caer tras un salto en el fondo de pista, gira hacia fuera la pierna de apoyo, lo que reduce claramente el impacto sobre el tendón de Aquiles.',
      injury40: 'A partir de los 41 años: la bajada de velocidad y potencia es más marcada, así que cuida el tendón de Aquiles, la rodilla y el hombro; haz 2 sesiones semanales de fuerza de piernas y core, reduce los remates en salto seguidos, y aumenta la carga de forma progresiva sin subidas bruscas.',
      injury50: 'A partir de los 51 años: prioriza los dobles y un juego más técnico; añade ejercicios de equilibrio y fuerza de piernas, con 2 sesiones semanales de trabajo de fuerza; si tienes alguna enfermedad crónica o llevas mucho tiempo sin hacer ejercicio, consulta a un médico antes de empezar un entrenamiento sistemático.',
      wingspanAssumed: 'No indicaste tu envergadura: el informe la ha estimado igual a tu altura, así que el resultado es solo orientativo.',
      closeCall: 'Tu estilo principal y tu segundo estilo tienen un encaje muy parecido: puedes tratarlos como un "doble estilo" — merece la pena entrenar los dos.',
      selfRatingHigh: 'En la etapa de principiante, es habitual valorarse a uno mismo con bastante desviación; te conviene hacer alguna prueba de campo (salto vertical, comba, reacción con regla) para calibrar tu autoevaluación.',
      bmiHigh: 'Tu proporción peso/altura es elevada: si es sobre todo masa muscular, es una ventaja de fuerza; si es sobre todo grasa, ralentizará tus desplazamientos y cargará más rodillas y tobillos. El IMC no distingue entre músculo y grasa, así que esto es solo un aviso, no un juicio sobre tu peso.',
      bmiLow: 'Tu peso es bajo: es posible que tu reserva de fuerza y de resistencia a la fatiga sea limitada; te conviene combinar trabajo de fuerza con una buena alimentación.',
    },
    referencesTitle: 'Referencias',
    references: [
      {
        id: 'leMansec2023',
        citation: 'Le Mansec Y, Boiveau M, Doron J, Jubeau M (2023). European singles and doubles badminton matches analysis with specific focus on pair doubles. Int J Racket Sports Sci, 5(1), 14–22.',
        url: 'https://doi.org/10.30827/ijrss.33244',
        usedFor: 'Reparto de roles entre zona de red y fondo de pista en dobles, y la recomendación de pareja complementaria; comparación de la carga de desplazamiento entre individuales y dobles.',
      },
      {
        id: 'abian2021',
        citation: 'Abián P, Simón-Chico L, Bravo-Sánchez A, Abián-Vicén J (2021). Elite badminton is getting older: ages of the top 100 ranked badminton players from 1994 to 2020. Int J Environ Res Public Health, 18(22), 11779.',
        url: 'https://doi.org/10.3390/ijerph182211779',
        usedFor: 'Recomendación para la etapa "dorada física" de 18–30 años.',
      },
      {
        id: 'kaalund1989',
        citation: 'Kaalund S, Lass P, Høgsaa B, Nøhr M (1989). Achilles tendon rupture in badminton. British Journal of Sports Medicine, 23(2), 102–104.',
        url: 'https://doi.org/10.1136/bjsm.23.2.102',
        usedFor: 'Riesgo de rotura del tendón de Aquiles entre los 31 y los 40 años, y el aviso de prevención de lesiones.',
      },
      {
        id: 'kaldau2022',
        citation: 'Kaldau NC, Nedergaard NJ, Hölmich P, Bencke J (2022). Adjusted landing technique reduces the load on the Achilles tendon in badminton players. Journal of Sports Science and Medicine, 21(2), 224–232.',
        url: 'https://doi.org/10.52082/jssm.2022.224',
        usedFor: 'Recomendación de entrenamiento: girar hacia fuera la pierna de apoyo al caer tras un salto en el fondo de pista, para reducir la carga sobre el tendón de Aquiles.',
      },
      {
        id: 'mann2007',
        citation: 'Mann DTY, Williams AM, Ward P, Janelle CM (2007). Perceptual-cognitive expertise in sport: a meta-analysis. Journal of Sport & Exercise Psychology, 29(4), 457–478.',
        url: 'https://doi.org/10.1123/jsep.29.4.457',
        usedFor: 'En el diagnóstico de "reacción", explica que la reacción depende sobre todo de la anticipación y la experiencia, no solo de una respuesta nerviosa simple.',
      },
      {
        id: 'zhangLeng2024',
        citation: 'Zhang Y, Leng B (2024). Performance of elite women’s singles badminton players: the influence of left-handed players. Journal of Human Kinetics, 92, 239–249.',
        url: 'https://doi.org/10.5114/jhk/172783',
        usedFor: 'Aviso táctico para jugar contra un rival zurdo, limitado a ese contexto concreto.',
      },
      {
        id: 'borde2015',
        citation: 'Borde R, Hortobágyi T, Granacher U (2015). Dose-response relationships of resistance training in healthy old adults: a systematic review and meta-analysis. Sports Medicine, 45(12), 1693–1720.',
        url: 'https://doi.org/10.1007/s40279-015-0385-9',
        usedFor: 'Recomendación de frecuencia, series e intensidad del trabajo de fuerza para personas de 51 años o más.',
      },
    ],
    disclaimer: 'Este informe se genera a partir de estimaciones corporales y de datos de autoevaluación o de pruebas de campo; es solo una referencia para el entrenamiento amateur, no sustituye la supervisión presencial de un entrenador o entrenadora cualificado/a ni constituye un consejo médico. Si tienes lesiones previas o alguna enfermedad crónica, consulta antes a un médico o a un/a fisioterapeuta.',
  },
}
